# **Matrices Homogeneas en un espacio tridimensional**

**Docente:** PhD Jorge Rudas

**Diseño de prototipos - 2025 I**

**INFOTEP**

In [44]:
import numpy as np
import math
from sympy import*
init_printing()

In [45]:
class GradosARadianes:
    """
    Convierte un valor en grados a radianes.

    Parametros:
        grados: Un número que representa el valor en grados a convertir.

    Métodos:
        convertir_a_radianes(): Convierte el valor en grados a radianes y lo retorna.
    """

    def __init__(self, grados):
        """
        Inicializa la clase con el valor en grados.

        Parametros:
            grados: Un número que representa el valor en grados.
        """
        self.grados = grados

    def convertir_a_radianes(self):
        """
        Convierte el valor almacenado en grados a radianes.

        Retorna:
            float: El valor equivalente en radianes.
        """
        return math.radians(self.grados)

### Declaración de variables simbolicas

In [46]:
## Variables Simbolicas
theta = symbols("theta",  real=True)
phi = symbols("phi",  real=True)
psi = symbols("psi",  real=True)
t_x, t_y, t_z = symbols("t_x t_y t_z", real=True)

### Rotacion eje x

In [47]:
H_x = Matrix([[1, 0, 0, 0], [0, cos(phi), -sin(phi), 0], [0, sin(phi), cos(phi), 0], [0, 0, 0, 1]])
H_x

⎡1    0        0     0⎤
⎢                     ⎥
⎢0  cos(φ)  -sin(φ)  0⎥
⎢                     ⎥
⎢0  sin(φ)  cos(φ)   0⎥
⎢                     ⎥
⎣0    0        0     1⎦

### Rotacion eje y

In [48]:
H_y = Matrix([[cos(theta), 0, sin(theta), 0], [0, 1, 0, 0], [-sin(theta), 0, cos(theta), 0], [0, 0, 0, 1]])
H_y


⎡cos(θ)   0  sin(θ)  0⎤
⎢                     ⎥
⎢   0     1    0     0⎥
⎢                     ⎥
⎢-sin(θ)  0  cos(θ)  0⎥
⎢                     ⎥
⎣   0     0    0     1⎦

### Rotacion eje z

In [49]:
H_z = Matrix([[cos(psi), -sin(psi), 0, 0], [sin(psi), cos(psi), 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
H_z

⎡cos(ψ)  -sin(ψ)  0  0⎤
⎢                     ⎥
⎢sin(ψ)  cos(ψ)   0  0⎥
⎢                     ⎥
⎢  0        0     1  0⎥
⎢                     ⎥
⎣  0        0     0  1⎦

# **H para rotacion y luego traslaciones**

In [50]:
# Matriz para traslación y luego rotación
H_xt = Matrix([[1, 0, 0, t_x], [0, cos(phi), -sin(phi), t_y], [0, sin(phi), cos(phi), t_z], [0, 0, 0, 1]])
H_xt

⎡1    0        0     tₓ ⎤
⎢                       ⎥
⎢0  cos(φ)  -sin(φ)  t_y⎥
⎢                       ⎥
⎢0  sin(φ)  cos(φ)   t_z⎥
⎢                       ⎥
⎣0    0        0      1 ⎦

In [51]:
# Matriz para traslación y luego rotación
H_yt = Matrix([[cos(theta), 0, sin(theta), t_x], [0, 1, 0, t_y], [-sin(theta), 0, cos(theta), t_z], [0, 0, 0, 1]])
H_yt

⎡cos(θ)   0  sin(θ)  tₓ ⎤
⎢                       ⎥
⎢   0     1    0     t_y⎥
⎢                       ⎥
⎢-sin(θ)  0  cos(θ)  t_z⎥
⎢                       ⎥
⎣   0     0    0      1 ⎦

In [52]:
H_zt = Matrix([[cos(psi), -sin(psi), 0, t_x], [sin(psi), cos(psi), 0, t_y], [0, 0, 1, t_z],[0, 0, 0, 1]])
H_zt

⎡cos(ψ)  -sin(ψ)  0  tₓ ⎤
⎢                       ⎥
⎢sin(ψ)  cos(ψ)   0  t_y⎥
⎢                       ⎥
⎢  0        0     1  t_z⎥
⎢                       ⎥
⎣  0        0     0   1 ⎦

# **H para Trasladación y luego rotación**

In [53]:
H_tx = Matrix([[1, 0, 0, t_x],[0, cos(phi), -sin(phi), t_y * cos(phi) - t_z * sin(phi)],[0, sin(phi), cos(phi), t_y * sin(phi) + t_z * cos(phi)], [0, 0, 0, 1]])
H_tx

⎡1    0        0               tₓ           ⎤
⎢                                           ⎥
⎢0  cos(φ)  -sin(φ)  t_y⋅cos(φ) - t_z⋅sin(φ)⎥
⎢                                           ⎥
⎢0  sin(φ)  cos(φ)   t_y⋅sin(φ) + t_z⋅cos(φ)⎥
⎢                                           ⎥
⎣0    0        0                1           ⎦

In [54]:
H_ty = Matrix([[cos(theta), 0, sin(theta), t_x * cos(theta) + t_z * sin(theta)], [0, 1, 0, t_y], [-sin(theta), 0, cos(theta), t_z * cos(theta) - t_x * sin(theta)], [0, 0, 0, 1]])
H_ty

⎡cos(θ)   0  sin(θ)  tₓ⋅cos(θ) + t_z⋅sin(θ) ⎤
⎢                                           ⎥
⎢   0     1    0               t_y          ⎥
⎢                                           ⎥
⎢-sin(θ)  0  cos(θ)  -tₓ⋅sin(θ) + t_z⋅cos(θ)⎥
⎢                                           ⎥
⎣   0     0    0                1           ⎦

In [55]:
H_tz = Matrix([[cos(psi), -sin(psi), 0, t_x * cos(psi) - t_y * sin(psi)], [sin(psi), cos(psi), 0, t_x * sin(psi) + t_y * cos(psi)], [0, 0, 1, t_z], [0, 0, 0, 1]])
H_tz

⎡cos(ψ)  -sin(ψ)  0  tₓ⋅cos(ψ) - t_y⋅sin(ψ)⎤
⎢                                          ⎥
⎢sin(ψ)  cos(ψ)   0  tₓ⋅sin(ψ) + t_y⋅cos(ψ)⎥
⎢                                          ⎥
⎢  0        0     1           t_z          ⎥
⎢                                          ⎥
⎣  0        0     0            1           ⎦

### Composicion de Matrices Homogeneas

Probando la conmutatividad de las matrices homogeneas

In [56]:
H = H_z@H_y@H_x
H

⎡cos(ψ)⋅cos(θ)  sin(φ)⋅sin(θ)⋅cos(ψ) - sin(ψ)⋅cos(φ)  sin(φ)⋅sin(ψ) + sin(θ)⋅cos(φ)⋅cos(ψ)   0⎤
⎢                                                                                             ⎥
⎢sin(ψ)⋅cos(θ)  sin(φ)⋅sin(ψ)⋅sin(θ) + cos(φ)⋅cos(ψ)  -sin(φ)⋅cos(ψ) + sin(ψ)⋅sin(θ)⋅cos(φ)  0⎥
⎢                                                                                             ⎥
⎢   -sin(θ)                sin(φ)⋅cos(θ)                          cos(φ)⋅cos(θ)              0⎥
⎢                                                                                             ⎥
⎣      0                         0                                      0                    1⎦

In [57]:
H = H_x@H_y@H_z
H

⎡           cos(ψ)⋅cos(θ)                         -sin(ψ)⋅cos(θ)                  sin(θ)      0⎤
⎢                                                                                              ⎥
⎢sin(φ)⋅sin(θ)⋅cos(ψ) + sin(ψ)⋅cos(φ)  -sin(φ)⋅sin(ψ)⋅sin(θ) + cos(φ)⋅cos(ψ)  -sin(φ)⋅cos(θ)  0⎥
⎢                                                                                              ⎥
⎢sin(φ)⋅sin(ψ) - sin(θ)⋅cos(φ)⋅cos(ψ)  sin(φ)⋅cos(ψ) + sin(ψ)⋅sin(θ)⋅cos(φ)   cos(φ)⋅cos(θ)   0⎥
⎢                                                                                              ⎥
⎣                 0                                      0                          0         1⎦

# **Experimento 1**
#### Comprobar que una secuencia de rotaciones produce el mismo resultado que una composición de matrices homogeneas

In [58]:
P0 = np.array([1, 1, 0])

1. Probando solo con matrices de rotación en 3D

In [59]:
#Matriz de rotacion 3D sobre el eje x
R_x = Matrix([[1, 0, 0], [0, cos(theta), -sin(theta)], [0, sin(theta), cos(theta)]])
R_x

⎡1    0        0   ⎤
⎢                  ⎥
⎢0  cos(θ)  -sin(θ)⎥
⎢                  ⎥
⎣0  sin(θ)  cos(θ) ⎦

In [60]:
#Matriz de rotacion 3D sobre el eje y
R_y = Matrix([[cos(theta), 0, sin(theta)], [0, 1, 0], [-sin(theta), 0, cos(theta)]])
R_y

⎡cos(θ)   0  sin(θ)⎤
⎢                  ⎥
⎢   0     1    0   ⎥
⎢                  ⎥
⎣-sin(θ)  0  cos(θ)⎦

In [61]:
theta_val = np.pi/9 # 20 grados en radianes
R_x_p0 = np.array(R_x.subs({theta: theta_val})).astype(np.float64) #Se convierte theta simbolico a un valor concreto Rx
R_y_p0 = np.array(R_y.subs({theta: theta_val})).astype(np.float64) #Se convierte theta simbolico a un valor concreto Ry

P0_rotado_x = np.dot(R_x_p0, P0) #Producto punto entre la matrix de rotación y el vector de posición del punto
P0_rotado_y = np.dot(R_y_p0, P0_rotado_x) #Producto punto entre la matrix de rotación y el vector de posición del punto

print(P0_rotado_y)

[ 1.0566704   0.93969262 -0.02062634]


2. Ahora probamos con la composición de matrices homogeneas

In [62]:
#Se convierte el punto 3D a un punto de coordenadas homogeneas

P0_homogeneo = np.append(P0, 1)
P0_homogeneo = np.reshape(P0_homogeneo, (4, 1))
print(P0)
print(P0_homogeneo)

[1 1 0]
[[1]
 [1]
 [0]
 [1]]


In [63]:
#Se realiza la composición de las matrices homogeneas para x y y
Hxy = H_y@H_x
Hxy

⎡cos(θ)   sin(φ)⋅sin(θ)  sin(θ)⋅cos(φ)  0⎤
⎢                                        ⎥
⎢   0        cos(φ)         -sin(φ)     0⎥
⎢                                        ⎥
⎢-sin(θ)  sin(φ)⋅cos(θ)  cos(φ)⋅cos(θ)  0⎥
⎢                                        ⎥
⎣   0           0              0        1⎦

In [64]:
theta_val = np.pi/9 # 20 grados en radianes
phi_val = np.pi/9 # 20 grados en radianes

Hxy_p0 = np.array(Hxy.subs({phi: phi_val, theta: theta_val})).astype(np.float64) #Se convierte theta simbolico a un valor concreto Rx
Hxy_p0

array([[ 0.93969262,  0.11697778,  0.3213938 ,  0.        ],
       [ 0.        ,  0.93969262, -0.34202014,  0.        ],
       [-0.34202014,  0.3213938 ,  0.88302222,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [65]:
P0_rotado_Hxy = np.dot(Hxy_p0, P0_homogeneo)
P0_rotado_Hxy

array([[ 1.0566704 ],
       [ 0.93969262],
       [-0.02062634],
       [ 1.        ]])

# **Actividad**

* Calcule las siguientes matrices homogeneas

In [66]:
from IPython.display import Image

Image(url='1.png')

## Donde:

In [67]:
Image(url='2.png')

# **Resultados aquí debajo**

In [68]:
H = H_z@H_y@H_x
theta_val = np.pi*56/180 # 20 grados en radianes
phi_val = np.pi*2/180
psi_val = np.pi*53/180

Hzyx = np.array(H.subs({phi: phi_val, theta: theta_val, psi: psi_val})).astype(np.float64) #Se convierte theta simbolico a un valor concreto Rx

Hzyx

array([[ 0.33653069, -0.78073669,  0.52649531,  0.        ],
       [ 0.44659131,  0.62455533,  0.64069247,  0.        ],
       [-0.82903757,  0.01951555,  0.55885226,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [69]:
np.dot(Hzyx, P0_homogeneo)

array([[-0.444206  ],
       [ 1.07114664],
       [-0.80952202],
       [ 1.        ]])

**Punto 2**

**para poder reaizar la actividad se realizo por paso:**

In [117]:
#Primero realizamos la matriz h_ty con valores 1

t1_x = 3
t1_y = 0
t1_z = 0

convertidor = GradosARadianes(6)
radianes = convertidor.convertir_a_radianes()
theta_val = radianes

H_ty1_subs = np.array(H_ty.subs({theta: theta_val, t_x: t1_x, t_y: t1_y, t_z: t1_z, psi: 0, phi: 0}))


#Segundo realizamos la matriz h_x
phi_val = np.pi*2/180

H_x_sub = np.array(H_x.subs({phi: phi_val})).astype(np.float64)

# Tercero realizamos la matriz h_ty con valores 2
t2_x = 1
t2_y = 1
t2_z = 0

convertidor = GradosARadianes(-16)
radianes = convertidor.convertir_a_radianes()
theta_val = radianes

H_ty2_subs = np.array(H_ty.subs({theta: theta_val, t_x: t2_x, t_y: t2_y, t_z: t2_z, psi: 0, phi: 0}))

# Multiplicación de las matrices
H_final = H_ty1_subs @ H_x_sub @H_ty2_subs

# Multiplicación de las matrices final y el punto
H_final = H_final.astype(np.float64) #convertimos a float64
resultado = np.dot(H_final, P0_homogeneo)
print(resultado)

[[4.96044207]
 [1.97954244]
 [0.10279361]
 [1.        ]]


**Punto 3**

In [118]:
#primera parte rotacion en el eje z: h_z y luego trasladacion
convertidor = GradosARadianes(53)
psi_val = convertidor.convertir_a_radianes()
t1_x = 3
t1_y = 0
t1_z = 0

H_zt_subs = np.array(H_zt.subs({psi: psi_val, t_x: t1_x, t_y: t1_y, t_z: t1_z,theta: 0, phi: 0})).astype(np.float64)

#Segunda parte, rotación en el eje y
convertidor = GradosARadianes(56)
theta_val = convertidor.convertir_a_radianes()

H_y_subs = np.array(H_y.subs({theta: theta_val})).astype(np.float64)

#tercera parte h(t2)
t2_x = 1
t2_y = 1
t2_z = 0
H_t2_subs = np.array(H.subs({t_x: t2_x, t_y: t2_y, t_z: t2_z, theta: 0, psi: 0, phi: 0})).astype(np.float64)

#cuarta parte, rotacion en el eje z
convertidor = GradosARadianes(53)
psi_val = convertidor.convertir_a_radianes()

H_z_subs = np.array(H_z.subs({psi: psi_val})).astype(np.float64)


# Multiplicación de las matrices
H_final = H_zt_subs @ H_y_subs @ H_t2_subs @ H_z_subs

resultado = np.dot(H_final, P0_homogeneo)
print(resultado)

[[1.81531434]
 [0.75491385]
 [0.16317158]
 [1.        ]]


**Observación: No encontramos matris (H), en la presetación para representar h(t2), asi que usamos la que dejo arriba en el codigo.**

**Punto 4**

**Realizada paso por paso**

In [121]:
#Primera parte, rotacion en eje y: H_Y
convertidor = GradosARadianes(56)
theta_val = convertidor.convertir_a_radianes()

H_y_subs = np.array(H_y.subs({theta: theta_val, t_x: 0, t_y: 0, t_z: 0, psi: 0, phi: 0})).astype(np.float64)

#Segunda parte rotacion en eje z: h_z y luego trasladación
convertidor = GradosARadianes(11)
psi1_val = convertidor.convertir_a_radianes()
t1_x = 3
t1_y = 0
t1_z = 0

H_zt_subs1 = np.array(H_tz.subs({psi: psi1_val, t_x: t1_x, t_y: t1_y, t_z: t1_z, theta: 0, phi: 0})).astype(np.float64)


#Tercera parte, rotacion en el eje z: h_z
convertidor = GradosARadianes(-3)
psi2_val = convertidor.convertir_a_radianes()

H_z_subs1 = np.array(H_z.subs({psi: psi2_val})).astype(np.float64)

#Cuarta parte, rotación en el eje x: h_x
convertidor = GradosARadianes(2)
phi_val = convertidor.convertir_a_radianes()

H_x_subs = np.array(H_x.subs({phi: phi_val})).astype(np.float64)

#quinta parte: rotacion en el eje z: h_z
convertidor = GradosARadianes(278)
psi3_val = convertidor.convertir_a_radianes()

H_z_subs2 = np.array(H_z.subs({psi: psi3_val, theta: 0, phi: 0})).astype(np.float64)

H_final = H_y_subs @ H_zt_subs1 @ H_z_subs1 @ H_x_subs @ H_z_subs2

resultado = np.dot(H_final, P0_homogeneo)
print(resultado)

[[ 2.31375696]
 [-0.11268394]
 [-3.48340301]
 [ 1.        ]]
