# **Matrices Homogeneas en un espacio tridimensional**

**Docente:** PhD Jorge Rudas

**Diseño de prototipos - 2025 I**

**INFOTEP**

In [98]:
import numpy as np
from sympy import*
init_printing()

### Declaración de variables simbolicas

In [99]:
## Variables Simbolicas
theta = symbols("theta",  real=True)
phi = symbols("phi",  real=True)
psi = symbols("psi",  real=True)

### Rotacion eje x

In [100]:
H_x = Matrix([[1, 0, 0, 0], [0, cos(phi), -sin(phi), 0], [0, sin(phi), cos(phi), 0], [0, 0, 0, 1]])
H_x

⎡1    0        0     0⎤
⎢                     ⎥
⎢0  cos(φ)  -sin(φ)  0⎥
⎢                     ⎥
⎢0  sin(φ)  cos(φ)   0⎥
⎢                     ⎥
⎣0    0        0     1⎦

### Rotacion eje y

In [101]:
H_y = Matrix([[cos(theta), 0, sin(theta), 0], [0, 1, 0, 0], [-sin(theta), 0, cos(theta), 0], [0, 0, 0, 1]])
H_y


⎡cos(θ)   0  sin(θ)  0⎤
⎢                     ⎥
⎢   0     1    0     0⎥
⎢                     ⎥
⎢-sin(θ)  0  cos(θ)  0⎥
⎢                     ⎥
⎣   0     0    0     1⎦

### Rotacion eje z

In [102]:
H_z = Matrix([[cos(psi), -sin(psi), 0, 0], [sin(psi), cos(psi), 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
H_z

⎡cos(ψ)  -sin(ψ)  0  0⎤
⎢                     ⎥
⎢sin(ψ)  cos(ψ)   0  0⎥
⎢                     ⎥
⎢  0        0     1  0⎥
⎢                     ⎥
⎣  0        0     0  1⎦

### Composicion de Matrices Homogeneas

Probando la conmutatividad de las matrices homogeneas

In [103]:
H = H_z@H_y@H_x
H

⎡cos(ψ)⋅cos(θ)  sin(φ)⋅sin(θ)⋅cos(ψ) - sin(ψ)⋅cos(φ)  sin(φ)⋅sin(ψ) + sin(θ)⋅cos(φ)⋅cos(ψ)   0⎤
⎢                                                                                             ⎥
⎢sin(ψ)⋅cos(θ)  sin(φ)⋅sin(ψ)⋅sin(θ) + cos(φ)⋅cos(ψ)  -sin(φ)⋅cos(ψ) + sin(ψ)⋅sin(θ)⋅cos(φ)  0⎥
⎢                                                                                             ⎥
⎢   -sin(θ)                sin(φ)⋅cos(θ)                          cos(φ)⋅cos(θ)              0⎥
⎢                                                                                             ⎥
⎣      0                         0                                      0                    1⎦

In [104]:
H = H_x@H_y@H_z
H

⎡           cos(ψ)⋅cos(θ)                         -sin(ψ)⋅cos(θ)                  sin(θ)      0⎤
⎢                                                                                              ⎥
⎢sin(φ)⋅sin(θ)⋅cos(ψ) + sin(ψ)⋅cos(φ)  -sin(φ)⋅sin(ψ)⋅sin(θ) + cos(φ)⋅cos(ψ)  -sin(φ)⋅cos(θ)  0⎥
⎢                                                                                              ⎥
⎢sin(φ)⋅sin(ψ) - sin(θ)⋅cos(φ)⋅cos(ψ)  sin(φ)⋅cos(ψ) + sin(ψ)⋅sin(θ)⋅cos(φ)   cos(φ)⋅cos(θ)   0⎥
⎢                                                                                              ⎥
⎣                 0                                      0                          0         1⎦

# **Experimento 1**
#### Comprobar que una secuencia de rotaciones produce el mismo resultado que una composición de matrices homogeneas

In [105]:
P0 = np.array([1, 1, 0])

1. Probando solo con matrices de rotación en 3D

In [106]:
#Matriz de rotacion 3D sobre el eje x
R_x = Matrix([[1, 0, 0], [0, cos(theta), -sin(theta)], [0, sin(theta), cos(theta)]])
R_x

⎡1    0        0   ⎤
⎢                  ⎥
⎢0  cos(θ)  -sin(θ)⎥
⎢                  ⎥
⎣0  sin(θ)  cos(θ) ⎦

In [107]:
#Matriz de rotacion 3D sobre el eje y
R_y = Matrix([[cos(theta), 0, sin(theta)], [0, 1, 0], [-sin(theta), 0, cos(theta)]])
R_y

⎡cos(θ)   0  sin(θ)⎤
⎢                  ⎥
⎢   0     1    0   ⎥
⎢                  ⎥
⎣-sin(θ)  0  cos(θ)⎦

In [108]:
theta_val = np.pi/9 # 20 grados en radianes
R_x_p0 = np.array(R_x.subs({theta: theta_val})).astype(np.float64) #Se convierte theta simbolico a un valor concreto Rx
R_y_p0 = np.array(R_y.subs({theta: theta_val})).astype(np.float64) #Se convierte theta simbolico a un valor concreto Ry

P0_rotado_x = np.dot(R_x_p0, P0) #Producto punto entre la matrix de rotación y el vector de posición del punto
P0_rotado_y = np.dot(R_y_p0, P0_rotado_x) #Producto punto entre la matrix de rotación y el vector de posición del punto

print(P0_rotado_y)

[ 1.0566704   0.93969262 -0.02062634]


2. Ahora probamos con la composición de matrices homogeneas

In [109]:
#Se convierte el punto 3D a un punto de coordenadas homogeneas

P0_homogeneo = np.append(P0, 1)
P0_homogeneo = np.reshape(P0_homogeneo, (4, 1))
print(P0)
print(P0_homogeneo)

[1 1 0]
[[1]
 [1]
 [0]
 [1]]


In [110]:
#Se realiza la composición de las matrices homogeneas para x y y
Hxy = H_y@H_x
Hxy

⎡cos(θ)   sin(φ)⋅sin(θ)  sin(θ)⋅cos(φ)  0⎤
⎢                                        ⎥
⎢   0        cos(φ)         -sin(φ)     0⎥
⎢                                        ⎥
⎢-sin(θ)  sin(φ)⋅cos(θ)  cos(φ)⋅cos(θ)  0⎥
⎢                                        ⎥
⎣   0           0              0        1⎦

In [111]:
theta_val = np.pi/9 # 20 grados en radianes
phi_val = np.pi/9 # 20 grados en radianes

Hxy_p0 = np.array(Hxy.subs({phi: phi_val, theta: theta_val})).astype(np.float64) #Se convierte theta simbolico a un valor concreto Rx
Hxy_p0

array([[ 0.93969262,  0.11697778,  0.3213938 ,  0.        ],
       [ 0.        ,  0.93969262, -0.34202014,  0.        ],
       [-0.34202014,  0.3213938 ,  0.88302222,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [112]:
P0_rotado_Hxy = np.dot(Hxy_p0, P0_homogeneo)
P0_rotado_Hxy

array([[ 1.0566704 ],
       [ 0.93969262],
       [-0.02062634],
       [ 1.        ]])

# **Actividad**

* Calcule las siguientes matrices homogeneas

In [113]:
from IPython.display import Image

Image(url='1.png')

In [114]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful

## Donde:

In [115]:
Image(url='2.png')

# **Resultados aquí debajo**

# **PUNTO 1**

In [116]:
"""
Calcula la matriz de transformación H a partir de las matrices de rotación en los ejes z, y, y x,
y luego evalúa esta matriz con valores específicos de los ángulos phi, theta y psi.

Variables:
- H: Matriz de transformación combinada.
- theta_val, phi_val, psi_val: Valores en radianes de los ángulos de rotación.
- Hzyx_p0: Matriz H evaluada con los valores específicos de los ángulos.
"""

H = H_z@H_y@H_x
theta_val = np.pi*56/180
phi_val = np.pi*2/180
psi_val = np.pi*53/180

Hzyx_p0 = np.array(H.subs({phi: phi_val, theta: theta_val, psi:psi_val})).astype(np.float64)

Hzyx_p0

array([[ 0.33653069, -0.78073669,  0.52649531,  0.        ],
       [ 0.44659131,  0.62455533,  0.64069247,  0.        ],
       [-0.82903757,  0.01951555,  0.55885226,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [117]:
"""
Aplica la transformación Hzyx_p0 al punto P0_homogeneo mediante el producto de matrices.
El resultado es el punto transformado en el nuevo sistema de coordenadas.
"""
np.dot(Hzyx_p0, P0_homogeneo)

array([[-0.444206  ],
       [ 1.07114664],
       [-0.80952202],
       [ 1.        ]])

# **PUNTO 2**

In [118]:
"""
Define las variables simbólicas tx, ty y tz, que representan traslaciones en los ejes x, y y z, respectivamente.
Estas variables se utilizan en cálculos simbólicos para representar desplazamientos en un espacio tridimensional.
"""

tx = symbols("tx",  real=True)
ty = symbols("ty",  real=True)
tz = symbols("tz",  real=True)



In [ ]:
"""
Define la matriz de transformación H_y para una rotación alrededor del eje Y con un desplazamiento en 3D.

- La matriz incluye una rotación en el eje Y por un ángulo theta.
- También incorpora traslaciones en los ejes X, Y y Z (tx, ty, tz).
- Se utiliza en cálculos de transformación homogénea en un espacio tridimensional.

H_y es una matriz de 4x4 en forma homogénea, donde la última fila (0,0,0,1) mantiene la estructura de transformación afín.
"""

H_y = Matrix([[cos(theta), 0, sin(theta), tx*cos(theta) + tz*sin(theta)], [0, 1, 0, ty], [-sin(theta), 0, cos(theta), tz*cos(theta) - tx*sin(theta)], [0, 0, 0, 1]])
H_y

In [119]:
"""
Define la matriz de transformación H_y para una rotación alrededor del eje Y con un desplazamiento en 3D
y luego evalúa la matriz con valores específicos para los parámetros de traslación y rotación.

- H_y: Matriz homogénea 4x4 que combina rotación en el eje Y y traslaciones en X, Y y Z.
- tx, ty, tz: Valores de traslación en los respectivos ejes.
- theta: Ángulo de rotación en torno al eje Y.
- H_0: Matriz H_y evaluada con valores específicos de theta y traslaciones.

Se utiliza para transformar coordenadas en un espacio tridimensional considerando rotaciones y desplazamientos.
"""

H_y = Matrix([[cos(theta), 0, sin(theta), tx*cos(theta) + tz*sin(theta)], [0, 1, 0, ty], [-sin(theta), 0, cos(theta), tz*cos(theta) - tx*sin(theta)], [0, 0, 0, 1]])
H_y

tx_val = 3
ty_val = 0
tz_val = 0
theta_val = np.pi*6/180

H_0 = np.array(H_y.subs({theta: theta_val, tx: tx_val, ty: ty_val, tz:tz_val})).astype(np.float64)
H_0



array([[ 0.9945219 ,  0.        ,  0.10452846,  2.98356569],
       [ 0.        ,  1.        ,  0.        ,  0.        ],
       [-0.10452846,  0.        ,  0.9945219 , -0.31358539],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [120]:
"""
Define la matriz de transformación H_x para una rotación alrededor del eje X en un espacio tridimensional
y luego evalúa la matriz con un valor específico para el ángulo phi.

- H_x: Matriz homogénea 4x4 que representa una rotación en el eje X.
- phi: Ángulo de rotación en torno al eje X.
- phi_val: Valor del ángulo phi en radianes.
- H_1: Matriz H_x evaluada con el valor específico de phi.

Se usa para transformar coordenadas aplicando una rotación alrededor del eje X.
"""
H_x = Matrix([[1, 0, 0, 0], [0, cos(phi), -sin(phi), 0], [0, sin(phi), cos(phi), 0], [0, 0, 0, 1]])
H_x
phi_val = np.pi*2/180

H_1 = np.array(H_x.subs({phi: phi_val,})).astype(np.float64) #Se convierte phi simbolico a un valor concreto
H_1



array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.99939083, -0.0348995 ,  0.        ],
       [ 0.        ,  0.0348995 ,  0.99939083,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [121]:
"""
Define la matriz de transformación H_y2 para una rotación alrededor del eje Y con un desplazamiento en 3D
y luego evalúa la matriz con valores específicos para los parámetros de traslación y rotación.

- H_y2: Matriz homogénea 4x4 que combina rotación en el eje Y y traslaciones en X, Y y Z.
- tx, ty, tz: Valores de traslación en los respectivos ejes.
- theta: Ángulo de rotación en torno al eje Y.
- theta_val: Valor del ángulo theta en radianes.
- H_2: Matriz H_y2 evaluada con valores específicos de theta y traslaciones.

Se usa para transformar coordenadas aplicando una rotación alrededor del eje Y junto con una traslación.
"""
H_y2 = Matrix([[cos(theta), 0, sin(theta), tx*cos(theta) + tz*sin(theta)], [0, 1, 0, ty], [-sin(theta), 0, cos(theta), tz*cos(theta) - tx*sin(theta)], [0, 0, 0, 1]])
H_y2
tx_val = 1
ty_val = 1
tz_val = 0
theta_val = np.pi*-6/180

H_2 = np.array(H_y2.subs({theta: theta_val, tx: tx_val, ty: ty_val, tz:tz_val})).astype(np.float64)
H_2

array([[ 0.9945219 ,  0.        , -0.10452846,  0.9945219 ],
       [ 0.        ,  1.        ,  0.        ,  1.        ],
       [ 0.10452846,  0.        ,  0.9945219 ,  0.10452846],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [122]:
"""
Calcula la matriz de transformación compuesta H multiplicando las matrices H_0, H_1 y H_2 en el orden dado.
Luego, aplica esta transformación al punto P0_homogeneo mediante el producto de matrices.

- H_0: Matriz de transformación que combina rotación en Y y traslación.
- H_1: Matriz de transformación que representa una rotación en X.
- H_2: Matriz de transformación que combina otra rotación en Y y traslación.
- H: Matriz de transformación resultante de la multiplicación H_0 * H_1 * H_2.
- P0_homogeneo: Punto en coordenadas homogéneas a transformar.
- P0_transformado: Resultado de la transformación aplicada a `P0_homogeneo`.

Este cálculo se usa para transformar un punto tridimensional considerando rotaciones y traslaciones en un sistema de referencia.
"""

H = H_0@H_1@H_2
H
np.dot(H, P0_homogeneo)

array([[ 4.99084836],
       [ 1.99148567],
       [-0.24429542],
       [ 1.        ]])

# **PUNTO 3**

In [123]:
"""
Define las variables simbólicas tx, ty y tz, que representan los desplazamientos en los ejes X, Y y Z, respectivamente.

- tx: Traslación en el eje X.
- ty: Traslación en el eje Y.
- tz: Traslación en el eje Z.

Estas variables se utilizan en cálculos simbólicos para representar desplazamientos en un espacio tridimensional
y se incorporan en matrices de transformación homogénea.
"""
tx = symbols("tx",  real=True)
ty = symbols("ty",  real=True)
tz = symbols("tz",  real=True)

In [124]:
"""
Define la matriz de transformación H_z para una rotación alrededor del eje Z con una traslación en 3D
y luego evalúa la matriz con valores específicos para los parámetros de traslación y rotación.

- H_z: Matriz homogénea 4x4 que combina rotación en el eje Z y traslaciones en X, Y y Z.
- tx, ty, tz: Valores de traslación en los respectivos ejes.
- psi: Ángulo de rotación en torno al eje Z.
- psi_val: Valor del ángulo psi en radianes.
- H_1: Matriz H_z evaluada con valores específicos de psi y traslaciones.

Se usa para transformar coordenadas aplicando una rotación alrededor del eje Z junto con una traslación.
"""
H_z = Matrix([[cos(psi), -sin(psi), 0, tx], [sin(psi), cos(psi), 0, ty], [0, 0, 1, tz], [0, 0, 0, 1] ])
H_z

tx_val = 3
ty_val = 0
tz_val = 0
psi_val = np.pi*53/180

H_1 = np.array(H_z.subs({psi: psi_val, tx: tx_val, ty: ty_val, tz:tz_val})).astype(np.float64)
H_1

array([[ 0.60181502, -0.79863551,  0.        ,  3.        ],
       [ 0.79863551,  0.60181502,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [125]:
"""
Define la matriz de transformación H_y para una rotación alrededor del eje Y en un espacio tridimensional
y luego evalúa la matriz con un valor específico para el ángulo theta.

- H_y: Matriz homogénea 4x4 que representa una rotación en el eje Y.
- theta: Ángulo de rotación en torno al eje Y.
- theta_val: Valor del ángulo theta en radianes.
- H_2: Matriz H_y evaluada con el valor específico de theta.

Se usa para transformar coordenadas aplicando una rotación alrededor del eje Y.
"""
H_y = Matrix([[cos(theta), 0, sin(theta), 0], [0, 1, 0, 0], [-sin(theta), 0, cos(theta), 0], [0, 0, 0, 1]])
H_y

theta_val = np.pi*56/180

H_2 = np.array(H_y.subs({theta: theta_val,})).astype(np.float64) #Se convierte theta simbolico a un valor concreto
H_2

array([[ 0.5591929 ,  0.        ,  0.82903757,  0.        ],
       [ 0.        ,  1.        ,  0.        ,  0.        ],
       [-0.82903757,  0.        ,  0.5591929 ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [126]:
"""
Define la matriz de traslación H_t2 en un espacio tridimensional y luego la evalúa como una matriz numérica.

- t2: Vector de traslación con componentes en X, Y y Z.
- H_t2: Matriz homogénea 4x4 que representa una traslación en el espacio tridimensional.
- H_3: Matriz H_t2 convertida a un array de tipo float64.

Se usa para trasladar coordenadas en el espacio sin aplicar rotaciones.
"""
t2 = [1, 1, 0]
H_t2 = Matrix([[1, 0, 0, t2[0]], [0, 1, 0, t2[1]], [0, 0, 1, t2[2]], [0, 0, 0, 1]])
H_t2

H_3 = np.array(H_t2.subs({})).astype(np.float64)
H_3

array([[1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [127]:
"""
Define la matriz de transformación H_z para una rotación alrededor del eje Z en un espacio tridimensional
y luego evalúa la matriz con un valor específico para el ángulo psi.

- H_z: Matriz homogénea 4x4 que representa una rotación en el eje Z.
- psi: Ángulo de rotación en torno al eje Z.
- psi_val: Valor del ángulo psi en radianes.
- H_4: Matriz H_z evaluada con el valor específico de psi.

Se usa para transformar coordenadas aplicando una rotación alrededor del eje Z sin traslación.
"""
H_z = Matrix([[cos(psi), -sin(psi), 0, 0], [sin(psi), cos(psi), 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
H_z

psi_val = np.pi*53/180

H_4 = np.array(H_z.subs({psi: psi_val,})).astype(np.float64) #Se convierte psi simbolico a un valor concreto
H_4

array([[ 0.60181502, -0.79863551,  0.        ,  0.        ],
       [ 0.79863551,  0.60181502,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [128]:
"""
Calcula la matriz de transformación H como el producto de múltiples matrices de transformación homogéneas
y la aplica a un punto en coordenadas homogéneas.

- H_1, H_2, H_3, H_4: Matrices de transformación homogéneas que incluyen rotaciones y traslaciones.
- H: Matriz de transformación resultante de multiplicar H_1, H_2, H_3 y H_4.
- P0_homogeneo: Punto en coordenadas homogéneas que será transformado.
- np.dot(H, P0_homogeneo): Producto de la matriz de transformación con el punto en coordenadas homogéneas.

Se usa para aplicar una secuencia de transformaciones a un punto en el espacio tridimensional.
"""
H = H_1@H_2@H_3@H_4
H
np.dot(H, P0_homogeneo)

array([[ 1.35320952],
       [ 1.80332018],
       [-0.66586599],
       [ 1.        ]])

# **PUNTO 4**

In [129]:
"""
Define variables simbólicas para representar los desplazamientos en los ejes X, Y y Z en un espacio tridimensional.

- tx: Traslación en el eje X.
- ty: Traslación en el eje Y.
- tz: Traslación en el eje Z.

Se usan en matrices de transformación homogénea para representar traslaciones en el espacio tridimensional.
"""
tx = symbols("tx",  real=True)
ty = symbols("ty",  real=True)
tz = symbols("tz",  real=True)

In [130]:
"""
Define la matriz de transformación H_y para una rotación alrededor del eje Y en un espacio tridimensional
y luego evalúa la matriz con un valor específico para el ángulo theta.

- H_y: Matriz homogénea 4x4 que representa una rotación en el eje Y.
- theta: Ángulo de rotación en torno al eje Y.
- theta_val: Valor del ángulo theta en radianes.
- H_1: Matriz H_y evaluada con el valor específico de theta.

Se usa para transformar coordenadas aplicando una rotación alrededor del eje Y sin traslación.
"""
H_y = Matrix([[cos(theta), 0, sin(theta), 0], [0, 1, 0, 0], [-sin(theta), 0, cos(theta), 0], [0, 0, 0, 1]])
H_y

theta_val = np.pi*56/180

H_1 = np.array(H_y.subs({theta: theta_val})).astype(np.float64) #Se convierte psi simbolico a un valor concreto
H_1

array([[ 0.5591929 ,  0.        ,  0.82903757,  0.        ],
       [ 0.        ,  1.        ,  0.        ,  0.        ],
       [-0.82903757,  0.        ,  0.5591929 ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [131]:
"""
Define la matriz de transformación homogénea H_z para una rotación alrededor del eje Z con traslación.

- H_z: Matriz homogénea 4x4 que representa una rotación en el eje Z con traslaciones en los ejes X, Y y Z.
- psi: Ángulo de rotación en torno al eje Z.
- tx: Traslación en el eje X.
- ty: Traslación en el eje Y.
- tz: Traslación en el eje Z.

Se usa en transformaciones espaciales para aplicar una rotación alrededor del eje Z junto con una traslación.
"""
H_z = Matrix([[cos(psi), -sin(psi), 0, tx], [sin(psi), cos(psi), 0, ty], [0, 0, 1, tz], [0, 0, 0, 1]])
H_z

⎡cos(ψ)  -sin(ψ)  0  tx⎤
⎢                      ⎥
⎢sin(ψ)  cos(ψ)   0  ty⎥
⎢                      ⎥
⎢  0        0     1  tz⎥
⎢                      ⎥
⎣  0        0     0  1 ⎦

In [132]:
"""
Asigna valores específicos a las variables de traslación (tx, ty, tz) y al ángulo de rotación psi para evaluar la matriz H_z.

- tx_val, ty_val, tz_val: Valores de traslación en los ejes X, Y y Z.
- psi_val: Valor del ángulo psi en radianes (conversión de grados a radianes).
- H_2: Matriz de transformación H_z evaluada con los valores específicos.

Se usa para obtener una matriz de transformación numérica aplicando una rotación en el eje Z y una traslación.
"""
tx_val = 3
ty_val = 0
tz_val = 0

psi_val = np.pi*11/180


H_2 = np.array(H_z.subs({tx: tx_val, ty: ty_val, tz: tz_val, psi: psi_val,})).astype(np.float64) #Se convierte psi simbolico a un valor concreto
H_2

array([[ 0.98162718, -0.190809  ,  0.        ,  3.        ],
       [ 0.190809  ,  0.98162718,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [133]:
"""
Define la matriz de transformación homogénea H_z para una rotación alrededor del eje Z sin traslación.

- H_z: Matriz homogénea 4x4 que representa una rotación en el eje Z sin desplazamientos en X, Y o Z.
- psi: Ángulo de rotación en torno al eje Z.

Se utiliza en transformaciones espaciales para aplicar una rotación pura alrededor del eje Z sin traslación.
"""
H_z = Matrix([[cos(psi), -sin(psi), 0, 0], [sin(psi), cos(psi), 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
H_z

⎡cos(ψ)  -sin(ψ)  0  0⎤
⎢                     ⎥
⎢sin(ψ)  cos(ψ)   0  0⎥
⎢                     ⎥
⎢  0        0     1  0⎥
⎢                     ⎥
⎣  0        0     0  1⎦

In [134]:
"""
Sustituye el valor del ángulo psi en la matriz de rotación H_z y la convierte en una matriz numérica.

- psi_val: Ángulo de rotación en torno al eje Z, en radianes (negativo indica rotación en sentido horario).
- H_3: Matriz de transformación H_z evaluada con el valor específico de psi.

Se usa para obtener una matriz de transformación numérica aplicando una rotación en el eje Z sin traslación.
"""
psi_val = np.pi*-3/180

H_3 = np.array(H_z.subs({psi: psi_val,})).astype(np.float64) #Se convierte psi simbolico a un valor concreto
H_3

array([[ 0.99862953,  0.05233596,  0.        ,  0.        ],
       [-0.05233596,  0.99862953,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [135]:
"""
Define la matriz de transformación homogénea H_x para una rotación alrededor del eje X y la evalúa con un valor específico de phi.

- H_x: Matriz homogénea 4x4 que representa una rotación en el eje X sin traslación.
- phi_val: Ángulo de rotación en torno al eje X, convertido a radianes.
- H_4: Matriz de transformación H_x evaluada con el valor específico de phi.

Se utiliza en transformaciones espaciales para aplicar una rotación pura alrededor del eje X sin traslación.
"""
H_x = Matrix([[1, 0, 0, 0], [0, cos(phi), -sin(phi), 0], [0, sin(phi), cos(phi), 0], [0, 0, 0, 1]])
H_x
phi_val = np.pi*2/180

H_4 = np.array(H_x.subs({phi: phi_val,})).astype(np.float64) #Se convierte phi simbolico a un valor concreto
H_4


array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.99939083, -0.0348995 ,  0.        ],
       [ 0.        ,  0.0348995 ,  0.99939083,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [136]:
"""
Define la matriz de transformación homogénea H_z para una rotación alrededor del eje Z sin traslación.

- H_z: Matriz homogénea 4x4 que representa una rotación en el eje Z sin desplazamiento en los ejes X, Y o Z.

Se utiliza en transformaciones espaciales para aplicar una rotación pura alrededor del eje Z sin traslación.
"""
H_z = Matrix([[cos(psi), -sin(psi), 0, 0], [sin(psi), cos(psi), 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
H_z

⎡cos(ψ)  -sin(ψ)  0  0⎤
⎢                     ⎥
⎢sin(ψ)  cos(ψ)   0  0⎥
⎢                     ⎥
⎢  0        0     1  0⎥
⎢                     ⎥
⎣  0        0     0  1⎦

In [137]:
"""
Sustituye el valor del ángulo psi en la matriz de transformación H_z y la convierte a tipo float64.

- psi_val: Ángulo de rotación en torno al eje Z, convertido a radianes.
- H_5: Matriz de transformación H_z evaluada con el valor específico de psi.

Esta matriz se usa para aplicar una rotación en el eje Z en transformaciones espaciales.
"""
psi_val = np.pi*278/180

H_5 = np.array(H_z.subs({psi: psi_val,})).astype(np.float64) #Se convierte psi simbolico a un valor concreto
H_5

array([[ 0.1391731 ,  0.99026807,  0.        ,  0.        ],
       [-0.99026807,  0.1391731 ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [138]:
"""
Calcula la matriz de transformación compuesta H mediante el producto de matrices y la aplica a un punto homogéneo.

- H: Matriz de transformación homogénea resultante de la multiplicación de H_1, H_2, H_3, H_4 y H_5.
- P0_homogeneo: Punto en coordenadas homogéneas al que se le aplicará la transformación.
- np.dot(H, P0_homogeneo): Multiplicación de la matriz de transformación H con el punto homogéneo para obtener su nueva posición transformada.

Este cálculo se usa en transformaciones espaciales para aplicar una secuencia de rotaciones y traslaciones a un punto en el espacio 3D.
"""
H = H_1@H_2@H_3@H_4@H_5
H
np.dot(H, P0_homogeneo)

array([[ 2.34457881],
       [-0.68511092],
       [-3.52909827],
       [ 1.        ]])