Matrices de rotación simples en un espacio tridimensional
Docente: Jorge Rudas

Diseño de prototipos - 2025 I

INFOTEP

In [ ]:
import numpy as np
from sympy import*
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
init_printing()

Función dibujar un vector punto en un espacio tridimencional

In [ ]:
def dibujar_punto(punto, label, x_lim = [0, 1], y_lim=[0, 1], z_lim=[0, 1]):
  """
  Dibuja un punto en un espacio tridimensional.

  Parametros:
    punto: Un vector NumPy de tres elementos representando las coordenadas (x, y, z) del punto.
    label: Una cadena de texto para etiquetar el punto en el gráfico.
    x_lim: Una lista de dos elementos que define los límites del eje x.
    y_lim: Una lista de dos elementos que define los límites del eje y.
    z_lim: Una lista de dos elementos que define los límites del eje z.
  """

  fig = plt.figure()
  ax = fig.add_subplot(111, projection='3d')

  ax.scatter(punto[0], punto[1], punto[2], color='b', label=label)

  ax.set_xlabel('X')
  ax.set_ylabel('Y')
  ax.set_zlabel('Z')
  ax.set_title('Espacio 3D')

  ax.quiver(0, 0, 0, punto[0], punto[1], punto[2], color='b')

  ax.set_xlim(x_lim)
  ax.set_ylim(y_lim)
  ax.set_zlim(z_lim)
  ax.legend()
  plt.show()

In [ ]:
## Angulo simbolico
theta = symbols("theta",  real=True)

Rotación en el eje x

In [ ]:
## Matrix de rotación simbolica sobre le eje X
R_x = Matrix([[1, 0, 0], [0, cos(theta), -sin(theta)], [0, sin(theta), cos(theta)]])
R_x

⎡1    0        0   ⎤
⎢                  ⎥
⎢0  cos(θ)  -sin(θ)⎥
⎢                  ⎥
⎣0  sin(θ)  cos(θ) ⎦

Definición de un punto de prueba en el espacio tridimencional

In [ ]:
P0 = np.array([1, 1, 0])
print(P0)

[1 1 0]


In [ ]:
dibujar_punto(P0, "Punto P0", y_lim=[-1,1])

Aplicación de la matrix de rotación

In [ ]:
theta_val = np.pi #180 grados en radianes
R_p0 = np.array(R_x.subs({theta: theta_val})).astype(np.float64) #Se convierte theta simbolico a un valor concreto

P0_rotado = np.dot(R_p0, P0) #Producto punto entre la matrix de rotación y el vector de posición del punto
print(P0_rotado)

[ 1.0000000e+00 -1.0000000e+00  1.2246468e-16]


In [ ]:
dibujar_punto(P0_rotado, "Punto P0 rotado", y_lim=[-1, 1])

Aplicación de la matrix de rotación

In [ ]:
theta_val = np.pi/4 # 45 grados en radianes
R_p0 = np.array(R_x.subs({theta: theta_val})).astype(np.float64) #Se convierte theta simbolico a un valor concreto

P0_rotado = np.dot(R_p0, P0) #Producto punto entre la matrix de rotación y el vector de posición del punto
print(P0_rotado)

[1.         0.70710678 0.70710678]


In [ ]:
dibujar_punto(P0_rotado, "Punto P0 rotado", y_lim=[0, 1])

Rotación en el eje y

In [ ]:
R_y = Matrix([[cos(theta), 0, sin(theta)], [0, 1, 0], [-sin(theta), 0, cos(theta)]])
R_y

⎡cos(θ)   0  sin(θ)⎤
⎢                  ⎥
⎢   0     1    0   ⎥
⎢                  ⎥
⎣-sin(θ)  0  cos(θ)⎦

Rotación en el eje z

In [ ]:
R_z = Matrix([[cos(theta), -sin(theta), 0], [sin(theta), cos(theta), 0], [0, 0, 1]])
R_z

⎡cos(θ)  -sin(θ)  0⎤
⎢                  ⎥
⎢sin(θ)  cos(θ)   0⎥
⎢                  ⎥
⎣  0        0     1⎦

Ilustración angulos de rotación

In [ ]:
from IPython.display import Image


Image(url='https://www.researchgate.net/publication/348803228/figure/fig7/AS:984434408955905@1611718861641/a-Pitch-yaw-and-roll-angles-of-an-aircraft-with-body-orientation-O-u-v-original.ppm')

Multiples rotaciones

In [ ]:
dibujar_punto(P0, "P0",x_lim=[-1, 1], y_lim=[-1, 1])

In [ ]:
theta_val = np.pi # 180 grados en radianes
R_x_p0 = np.array(R_x.subs({theta: theta_val})).astype(np.float64) #Se convierte theta simbolico a un valor concreto Rx
R_y_p0 = np.array(R_y.subs({theta: theta_val})).astype(np.float64) #Se convierte theta simbolico a un valor concreto Ry
R_z_p0 = np.array(R_z.subs({theta: theta_val})).astype(np.float64) #Se convierte theta simbolico a un valor concreto Rz

P0_rotado_x = np.dot(R_x_p0, P0) #Producto punto entre la matrix de rotación y el vector de posición del punto
P0_rotado_y = np.dot(R_y_p0, P0_rotado_x) #Producto punto entre la matrix de rotación y el vector de posición del punto
P0_rotado_z = np.dot(R_z_p0, P0_rotado_y) #Producto punto entre la matrix de rotación y el vector de posición del punto

print(P0)
print(P0_rotado_x)
print(P0_rotado_y)
print(P0_rotado_z)

[1 1 0]
[ 1.0000000e+00 -1.0000000e+00  1.2246468e-16]
[-1.0000000e+00 -1.0000000e+00 -2.4492936e-16]
[ 1.0000000e+00  1.0000000e+00 -2.4492936e-16]


In [ ]:
dibujar_punto(P0_rotado_x, label = 'Rotacion X', x_lim=[-1, 1], y_lim=[-1, 1])
dibujar_punto(P0_rotado_y, label = 'Rotacion Y', x_lim=[-1, 1], y_lim=[-1, 1])
dibujar_punto(P0_rotado_z, label = 'Rotacion Z', x_lim=[-1, 1], y_lim=[-1, 1])

Actividad

1-Evalue el efecto del orden de las rotaciones y saque sus propias conclusiones



2-Agregue una función que re utilice la implementación compartida para hacer traslaciones

solucion

punto1 Evaluación del orden de las rotaciones:

# Evaluación del efecto del orden de las rotaciones:
# En las rotaciones 3D, el orden en que se aplican las rotaciones sí afecta el resultado final.
# Las rotaciones no son conmutativas, lo que significa que cambiar el orden de las rotaciones
# produce un resultado diferente. Por ejemplo, rotar primero alrededor del eje X y luego alrededor del eje Y
# no es lo mismo que rotar primero alrededor del eje Y y luego alrededor del eje X.
#
# Esto ocurre porque las rotaciones modifican las coordenadas del punto en diferentes formas
# y la siguiente rotación se aplica sobre esas nuevas coordenadas. Esto se puede verificar al comparar
# los resultados de las rotaciones en distintos órdenes.

# Conclusión:
# El orden de las rotaciones es importante en los espacios tridimensionales.
# El efecto final de las rotaciones depende del orden específico de los ejes alrededor de los cuales
# se realiza la rotación. Es crucial tener en cuenta el orden de rotación si se quiere obtener un resultado
# específico en el espacio 3D.

punto2 Función de traslación:

# Función de Traslación:
# La función 'traslacion' permite trasladar un punto en el espacio 3D utilizando un vector de traslación.
# La implementación de esta función es reutilizable, ya que se puede usar para trasladar cualquier punto
# en 3D por cualquier vector dado. Esta flexibilidad permite aplicar traslaciones múltiples a diferentes puntos
# sin tener que escribir el código de nuevo.

# Conclusión:
# La función 'traslacion' facilita la manipulación de puntos en el espacio 3D.
# Además, su reutilización mejora la eficiencia del código al permitir traslaciones de manera sencilla
# y consistente en cualquier punto.