# **Matrices Homogeneas en un espacio tridimensional**

**Docente:** PhD Jorge Rudas

**Diseño de prototipos - 2025 I**

**INFOTEP**

In [ ]:
import numpy as np
from sympy import*
init_printing()

### Declaración de variables simbolicas

In [ ]:
## Variables Simbolicas
theta = symbols("theta",  real=True)
phi = symbols("phi",  real=True)
psi = symbols("psi",  real=True)

### Rotacion eje x

In [ ]:
H_x = Matrix([[1, 0, 0, 0], [0, cos(phi), -sin(phi), 0], [0, sin(phi), cos(phi), 0], [0, 0, 0, 1]])
H_x

⎡1    0        0     0⎤
⎢                     ⎥
⎢0  cos(φ)  -sin(φ)  0⎥
⎢                     ⎥
⎢0  sin(φ)  cos(φ)   0⎥
⎢                     ⎥
⎣0    0        0     1⎦

### Rotacion eje y

In [ ]:
H_y = Matrix([[cos(theta), 0, sin(theta), 0], [0, 1, 0, 0], [-sin(theta), 0, cos(theta), 0], [0, 0, 0, 1]])
H_y


⎡cos(θ)   0  sin(θ)  0⎤
⎢                     ⎥
⎢   0     1    0     0⎥
⎢                     ⎥
⎢-sin(θ)  0  cos(θ)  0⎥
⎢                     ⎥
⎣   0     0    0     1⎦

### Rotacion eje z

In [ ]:
H_z = Matrix([[cos(psi), -sin(psi), 0, 0], [sin(psi), cos(psi), 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
H_z

⎡cos(ψ)  -sin(ψ)  0  0⎤
⎢                     ⎥
⎢sin(ψ)  cos(ψ)   0  0⎥
⎢                     ⎥
⎢  0        0     1  0⎥
⎢                     ⎥
⎣  0        0     0  1⎦

### Composicion de Matrices Homogeneas

Probando la conmutatividad de las matrices homogeneas

In [ ]:
H = H_z@H_y@H_x
H

⎡cos(ψ)⋅cos(θ)  sin(φ)⋅sin(θ)⋅cos(ψ) - sin(ψ)⋅cos(φ)  sin(φ)⋅sin(ψ) + sin(θ)⋅cos(φ)⋅cos(ψ)   0⎤
⎢                                                                                             ⎥
⎢sin(ψ)⋅cos(θ)  sin(φ)⋅sin(ψ)⋅sin(θ) + cos(φ)⋅cos(ψ)  -sin(φ)⋅cos(ψ) + sin(ψ)⋅sin(θ)⋅cos(φ)  0⎥
⎢                                                                                             ⎥
⎢   -sin(θ)                sin(φ)⋅cos(θ)                          cos(φ)⋅cos(θ)              0⎥
⎢                                                                                             ⎥
⎣      0                         0                                      0                    1⎦

In [ ]:
H = H_x@H_y@H_z
H

⎡           cos(ψ)⋅cos(θ)                         -sin(ψ)⋅cos(θ)                  sin(θ)      0⎤
⎢                                                                                              ⎥
⎢sin(φ)⋅sin(θ)⋅cos(ψ) + sin(ψ)⋅cos(φ)  -sin(φ)⋅sin(ψ)⋅sin(θ) + cos(φ)⋅cos(ψ)  -sin(φ)⋅cos(θ)  0⎥
⎢                                                                                              ⎥
⎢sin(φ)⋅sin(ψ) - sin(θ)⋅cos(φ)⋅cos(ψ)  sin(φ)⋅cos(ψ) + sin(ψ)⋅sin(θ)⋅cos(φ)   cos(φ)⋅cos(θ)   0⎥
⎢                                                                                              ⎥
⎣                 0                                      0                          0         1⎦

# **Experimento 1**
#### Comprobar que una secuencia de rotaciones produce el mismo resultado que una composición de matrices homogeneas

In [ ]:
P0 = np.array([1, 1, 0])

1. Probando solo con matrices de rotación en 3D

In [ ]:
#Matriz de rotacion 3D sobre el eje x
R_x = Matrix([[1, 0, 0], [0, cos(theta), -sin(theta)], [0, sin(theta), cos(theta)]])
R_x

⎡1    0        0   ⎤
⎢                  ⎥
⎢0  cos(θ)  -sin(θ)⎥
⎢                  ⎥
⎣0  sin(θ)  cos(θ) ⎦

In [ ]:
#Matriz de rotacion 3D sobre el eje y
R_y = Matrix([[cos(theta), 0, sin(theta)], [0, 1, 0], [-sin(theta), 0, cos(theta)]])
R_y

⎡cos(θ)   0  sin(θ)⎤
⎢                  ⎥
⎢   0     1    0   ⎥
⎢                  ⎥
⎣-sin(θ)  0  cos(θ)⎦

In [ ]:
theta_val = np.pi/9 # 20 grados en radianes
R_x_p0 = np.array(R_x.subs({theta: theta_val})).astype(np.float64) #Se convierte theta simbolico a un valor concreto Rx
R_y_p0 = np.array(R_y.subs({theta: theta_val})).astype(np.float64) #Se convierte theta simbolico a un valor concreto Ry

P0_rotado_x = np.dot(R_x_p0, P0) #Producto punto entre la matrix de rotación y el vector de posición del punto
P0_rotado_y = np.dot(R_y_p0, P0_rotado_x) #Producto punto entre la matrix de rotación y el vector de posición del punto

print(P0_rotado_y)

[ 1.0566704   0.93969262 -0.02062634]


2. Ahora probamos con la composición de matrices homogeneas

In [ ]:
#Se convierte el punto 3D a un punto de coordenadas homogeneas

P0_homogeneo = np.append(P0, 1)
P0_homogeneo = np.reshape(P0_homogeneo, (4, 1))
print(P0)
print(P0_homogeneo)

[1 1 0]
[[1]
 [1]
 [0]
 [1]]


In [ ]:
#Se realiza la composición de las matrices homogeneas para x y y
Hxy = H_y@H_x
Hxy

⎡cos(θ)   sin(φ)⋅sin(θ)  sin(θ)⋅cos(φ)  0⎤
⎢                                        ⎥
⎢   0        cos(φ)         -sin(φ)     0⎥
⎢                                        ⎥
⎢-sin(θ)  sin(φ)⋅cos(θ)  cos(φ)⋅cos(θ)  0⎥
⎢                                        ⎥
⎣   0           0              0        1⎦

In [ ]:
theta_val = np.pi/9 # 20 grados en radianes
phi_val = np.pi/9 # 20 grados en radianes

Hxy_p0 = np.array(Hxy.subs({phi: phi_val, theta: theta_val})).astype(np.float64) #Se convierte theta simbolico a un valor concreto Rx
Hxy_p0

array([[ 0.93969262,  0.11697778,  0.3213938 ,  0.        ],
       [ 0.        ,  0.93969262, -0.34202014,  0.        ],
       [-0.34202014,  0.3213938 ,  0.88302222,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:
P0_rotado_Hxy = np.dot(Hxy_p0, P0_homogeneo)
P0_rotado_Hxy

array([[ 1.0566704 ],
       [ 0.93969262],
       [-0.02062634],
       [ 1.        ]])

# **Actividad**

* Calcule las siguientes matrices homogeneas

In [ ]:
from IPython.display import Image

Image(url='1.png')

## Donde:

In [ ]:
Image(url='2.png')

# **Resultados aquí debajo**

# Primer ejercicio

In [ ]:
H = H_z@H_y@H_x
theta_val = np.pi*56/180
phi_val = np.pi*2/180
psi_val = np.pi*53/180

Hzyx = np.array(H.subs({phi: phi_val, theta: theta_val, psi: psi_val})).astype(np.float64) #Se convierte theta simbolico a un valor concreto Rx

Hzyx


array([[ 0.33653069, -0.78073669,  0.52649531,  0.        ],
       [ 0.44659131,  0.62455533,  0.64069247,  0.        ],
       [-0.82903757,  0.01951555,  0.55885226,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:
np.dot(Hzyx, P0_homogeneo)

array([[-0.444206  ],
       [ 1.07114664],
       [-0.80952202],
       [ 1.        ]])

# Segundo ejercicio

In [ ]:
"""
Declaramos las variables que necesitamos (x,y,z)
"""
t_x = symbols("t_x", real=True)
t_y = symbols("t_y", real=True)
t_z = symbols("t_z", real=True)


In [ ]:
"""
Se definen las matrices homogeneas que necesitamos
Matriz homogénea de rotación en el eje Y y traslación
H(t1, (y, θ1))
"""
H_y1_t1 = Matrix([[cos(theta), 0, sin(theta), t_x*cos(theta) + t_z*sin(theta)], [0, 1, 0, t_y], [-sin(theta), 0, cos(theta), t_z*cos(theta) - t_x*sin(theta)], [0, 0, 0, 1]])
H_y1_t1

"""
Valores de x, y, z
Y theta en radianes
"""

t_x_val = 3
t_y_val = 0
t_z_val = 0
theta_val = np.pi*6/180

Hxyt = np.array(H_y1_t1.subs({ theta: theta_val, t_x: t_x_val, t_y: t_y_val, t_z: t_z_val})).astype(np.float64)
Hxyt

array([[ 0.9945219 ,  0.        ,  0.10452846,  2.98356569],
       [ 0.        ,  1.        ,  0.        ,  0.        ],
       [-0.10452846,  0.        ,  0.9945219 , -0.31358539],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:
"""
Matriz homogenea de rotacion en el eje X
H(x, φ)
"""
H_x_phi = Matrix([[1, 0, 0, 0], [0, cos(phi), -sin(phi), 0], [0, sin(phi), cos(phi), 0], [0, 0, 0, 1]])
H_x_phi

"""
Valor de Phi en radianes
"""
phi_val = np.pi*2/180

Hxp = np.array(H_x_phi.subs({phi: phi_val})).astype(np.float64)
Hxp

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.99939083, -0.0348995 ,  0.        ],
       [ 0.        ,  0.0348995 ,  0.99939083,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:
"""
Matriz homogénea de rotacion en el eje Y y traslación
H(t2, (y, θ2))
"""
H_y2_t2 = Matrix([[cos(theta), 0, sin(theta), t_x*cos(theta) + t_z*sin(theta)], [0, 1, 0, t_y], [-sin(theta), 0, cos(theta), t_z*cos(theta) - t_x*sin(theta)], [0, 0, 0, 1]])
H_y2_t2

"""
Valores de x, y, z
Y theta en radianes
"""
t_x_val = 1
t_y_val = 1
t_z_val = 0
theta_val = np.pi*-6/180

Hxytz = np.array(H_y2_t2.subs({ theta: theta_val, t_x:t_x_val, t_y: t_y_val, t_z: t_z_val})).astype(np.float64)
Hxytz

array([[ 0.9945219 ,  0.        , -0.10452846,  0.9945219 ],
       [ 0.        ,  1.        ,  0.        ,  1.        ],
       [ 0.10452846,  0.        ,  0.9945219 ,  0.10452846],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:
"""
Se multiplican las matrices (cuando multiplicamos las matrices homogéneas aplicamos transformaciones para dimensión 3D)
"""
H2 = Hxyt@Hxp@Hxytz
H2


array([[ 9.99993344e-01,  3.64799076e-03, -6.33270922e-05,
         3.98720702e+00],
       [-3.64799076e-03,  9.99390827e-01, -3.47083136e-02,
         9.95742836e-01],
       [-6.33270922e-05,  3.47083136e-02,  9.99397483e-01,
        -2.78940403e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

In [ ]:
np.dot(H2, P0_homogeneo)

array([[ 4.99084836],
       [ 1.99148567],
       [-0.24429542],
       [ 1.        ]])

# Tercer ejercicio

In [ ]:
"""
Se definen las variables necesarias
"""
t_x = symbols("t_x", real=True)
t_y = symbols("t_y", real=True)
t_z = symbols("t_z", real=True)

In [ ]:
"""
Matriz homogénea de rotación en el eje Z y traslación
H((z, Ψ), t1)
"""
H_z_psi_t1 = Matrix([[cos(psi), -sin(psi), 0, t_x], [sin(psi), cos(psi), 0, t_y], [0, 0, 1, t_z], [0, 0, 0, 1]])
H_z_psi_t1

"""
Valores de x, y, z
Y psi en radianes
"""
psi_val = np.pi * 53 / 180
t_x_val = 3
t_y_val = 0
t_z_val = 0

H_z_ps = np.array(H_z_psi_t1.subs({ psi: psi_val, t_x: t_x_val, t_y: t_y_val, t_z: t_z_val})).astype(np.float64)
H_z_ps

array([[ 0.60181502, -0.79863551,  0.        ,  3.        ],
       [ 0.79863551,  0.60181502,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:
"""
Matriz homogénea de rotación en el eje Y
H(y, θ)
"""
H_y_theta = Matrix([[cos(theta), 0, sin(theta), 0], [0, 1, 0, 0], [-sin(theta), 0, cos(theta), 0], [0, 0, 0, 1]])
H_y_theta

"""
Valor de theta en radianes
"""

theta_val = np.pi * 56 / 180

H_y_th = np.array(H_y_theta.subs({theta: theta_val})).astype(np.float64)
H_y_th

array([[ 0.5591929 ,  0.        ,  0.82903757,  0.        ],
       [ 0.        ,  1.        ,  0.        ,  0.        ],
       [-0.82903757,  0.        ,  0.5591929 ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:
"""
Matriz homogénea de traslación
H(t2)
"""
H_t2 = Matrix([[1, 0, 0, t_x], [0, 1, 0, t_y], [0, 0, 1, t_z], [0, 0, 0, 1]])
H_t2

"""
Valores en x, y, z
"""
t_x_val = 1
t_y_val = 1
t_z_val = 0

H_t = np.array(H_t2.subs({t_x: t_x_val, t_y: t_y_val, t_z: t_z_val})).astype(np.float64)
H_t

array([[1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
"""
Matriz homogénea de rotación en el eje Z
H(z, Ψ)
"""
H_z_psi = Matrix([[cos(psi), -sin(psi), 0, 0], [sin(psi), cos(psi), 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
H_z_psi

"""
Valor de Psi en radianes
"""
psi_val = np.pi * 53 / 180

H_z_p = np.array(H_z_psi.subs({psi: psi_val})).astype(np.float64)
H_z_p

array([[ 0.60181502, -0.79863551,  0.        ,  0.        ],
       [ 0.79863551,  0.60181502,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:
"""
Se multiplican las matrices
"""
H3 = H_z_ps@H_y_th@H_t@H_z_p
H3

array([[-0.43528945, -0.74939621,  0.49892727,  2.53789518],
       [ 0.74939621,  0.00551764,  0.66209884,  1.04840633],
       [-0.49892727,  0.66209884,  0.5591929 , -0.82903757],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:
np.dot(H3, P0_homogeneo)

array([[ 1.35320952],
       [ 1.80332018],
       [-0.66586599],
       [ 1.        ]])

# Cuarto ejercicio

In [ ]:
"""
Variables para calcular la matriz homogenea
"""
t_x = symbols("t_x", real=True)
t_y = symbols("t_y", real=True)
t_z = symbols("t_z", real=True)

In [ ]:
"""
Matriz homogénea de rotación en el eje Y
H(y, 0)
"""
H_y_the = Matrix([[cos(theta), 0, sin(theta), 0], [0, 1, 0, 0], [-sin(theta), 0, cos(theta), 0], [0, 0, 0, 1]])
H_y_the

"""
Valor de theta en radianes
"""
theta_val = np.pi*56/180

H_y_th = np.array(H_y_the.subs({theta: theta_val})).astype(np.float64)
H_y_th

array([[ 0.5591929 ,  0.        ,  0.82903757,  0.        ],
       [ 0.        ,  1.        ,  0.        ,  0.        ],
       [-0.82903757,  0.        ,  0.5591929 ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:
"""
Matriz homogénea de rotación en el eje Z y traslación
H((z, Ψ1), t1)
"""
H_zpsi1_t1 = Matrix([[cos(psi), -sin(psi), 0, t_x], [sin(psi), cos(psi), 0, t_y], [0, 0, 1, t_z], [0, 0, 0, 1]])
H_zpsi1_t1

"""
Valores de x, y, z
Y psi en radianes
"""

psi_val = np.pi*11/180
t_x_val = 3
t_y_val = 0
t_z_val = 0

H_zp = np.array(H_zpsi1_t1.subs({ psi: psi_val, t_x: t_x_val, t_y: t_y_val, t_z: t_z_val})).astype(np.float64)
H_zp

array([[ 0.98162718, -0.190809  ,  0.        ,  3.        ],
       [ 0.190809  ,  0.98162718,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:
"""
Matriz homogenea de rotación en el eje Z
H(z, Ψ2)
"""
H_zpsi2 = Matrix([[cos(psi), -sin(psi), 0, 0], [sin(psi), cos(psi), 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
H_zpsi2

psi_val = np.pi*-3/180

Hz_p = np.array(H_zpsi2.subs({psi: psi_val})).astype(np.float64)
Hz_p

array([[ 0.99862953,  0.05233596,  0.        ,  0.        ],
       [-0.05233596,  0.99862953,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:
"""
Matriz homogénea de rotación en el eje X
H((x, φ)
"""

H_x_phi = Matrix([[1, 0, 0, 0], [0, cos(phi), -sin(phi), 0], [0, sin(phi), cos(phi), 0], [0, 0, 0, 1]])
H_x_phi

"""
Valor de Phi en radianes
"""

phi_val = np.pi*2/180

H_xp = np.array(H_x_phi.subs({phi: phi_val})).astype(np.float64)
H_xp

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.99939083, -0.0348995 ,  0.        ],
       [ 0.        ,  0.0348995 ,  0.99939083,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:
"""
Matriz homogénea de rotación en el eje Z
H(z, Ψ3)
"""
H_z_psi3 = Matrix([[cos(psi), -sin(psi), 0, 0], [sin(psi), cos(psi), 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
H_z_psi3

"""
Valor de Psi en radianes
"""
psi_val = np.pi*278/180

H_z_p = np.array(H_z_psi3.subs({psi: psi_val})).astype(np.float64)
H_z_p

array([[ 0.1391731 ,  0.99026807,  0.        ,  0.        ],
       [-0.99026807,  0.1391731 ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:
"""
Se multiplica las matrices
"""
H4 = H_y_th @ H_zp @ Hz_p @ H_xp @ H_z_p
H4


array([[ 0.12543609,  0.54156401,  0.83124859,  1.67757871],
       [-0.96066432,  0.2755534 , -0.03455986,  0.        ],
       [-0.24776975, -0.79421581,  0.55482556, -2.48711272],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:
np.dot(H4, P0_homogeneo)

array([[ 2.34457881],
       [-0.68511092],
       [-3.52909827],
       [ 1.        ]])