# **Matrices Homogeneas en un espacio tridimensional**

**Docente:** PhD Jorge Rudas

**Diseño de prototipos - 2025 I**

**INFOTEP**

In [ ]:
import numpy as np
from sympy import*
init_printing()

### Declaración de variables simbolicas

In [ ]:
## Variables Simbolicas
theta = symbols("theta",  real=True)
phi = symbols("phi",  real=True)
psi = symbols("psi",  real=True)

### Rotacion eje x

In [ ]:
H_x = Matrix([[1, 0, 0, 0], [0, cos(phi), -sin(phi), 0], [0, sin(phi), cos(phi), 0], [0, 0, 0, 1]])
H_x

⎡1    0        0     0⎤
⎢                     ⎥
⎢0  cos(φ)  -sin(φ)  0⎥
⎢                     ⎥
⎢0  sin(φ)  cos(φ)   0⎥
⎢                     ⎥
⎣0    0        0     1⎦

### Rotacion eje y

In [ ]:
H_y = Matrix([[cos(theta), 0, sin(theta), 0], [0, 1, 0, 0], [-sin(theta), 0, cos(theta), 0], [0, 0, 0, 1]])
H_y


⎡cos(θ)   0  sin(θ)  0⎤
⎢                     ⎥
⎢   0     1    0     0⎥
⎢                     ⎥
⎢-sin(θ)  0  cos(θ)  0⎥
⎢                     ⎥
⎣   0     0    0     1⎦

### Rotacion eje z

In [ ]:
H_z = Matrix([[cos(psi), -sin(psi), 0, 0], [sin(psi), cos(psi), 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
H_z

⎡cos(ψ)  -sin(ψ)  0  0⎤
⎢                     ⎥
⎢sin(ψ)  cos(ψ)   0  0⎥
⎢                     ⎥
⎢  0        0     1  0⎥
⎢                     ⎥
⎣  0        0     0  1⎦

### Composicion de Matrices Homogeneas

Probando la conmutatividad de las matrices homogeneas

In [ ]:
H = H_z@H_y@H_x
H

⎡cos(ψ)⋅cos(θ)  sin(φ)⋅sin(θ)⋅cos(ψ) - sin(ψ)⋅cos(φ)  sin(φ)⋅sin(ψ) + sin(θ)⋅cos(φ)⋅cos(ψ)   0⎤
⎢                                                                                             ⎥
⎢sin(ψ)⋅cos(θ)  sin(φ)⋅sin(ψ)⋅sin(θ) + cos(φ)⋅cos(ψ)  -sin(φ)⋅cos(ψ) + sin(ψ)⋅sin(θ)⋅cos(φ)  0⎥
⎢                                                                                             ⎥
⎢   -sin(θ)                sin(φ)⋅cos(θ)                          cos(φ)⋅cos(θ)              0⎥
⎢                                                                                             ⎥
⎣      0                         0                                      0                    1⎦

In [ ]:
H = H_x@H_y@H_z
H

⎡           cos(ψ)⋅cos(θ)                         -sin(ψ)⋅cos(θ)                  sin(θ)      0⎤
⎢                                                                                              ⎥
⎢sin(φ)⋅sin(θ)⋅cos(ψ) + sin(ψ)⋅cos(φ)  -sin(φ)⋅sin(ψ)⋅sin(θ) + cos(φ)⋅cos(ψ)  -sin(φ)⋅cos(θ)  0⎥
⎢                                                                                              ⎥
⎢sin(φ)⋅sin(ψ) - sin(θ)⋅cos(φ)⋅cos(ψ)  sin(φ)⋅cos(ψ) + sin(ψ)⋅sin(θ)⋅cos(φ)   cos(φ)⋅cos(θ)   0⎥
⎢                                                                                              ⎥
⎣                 0                                      0                          0         1⎦

# **Experimento 1**
#### Comprobar que una secuencia de rotaciones produce el mismo resultado que una composición de matrices homogeneas

In [ ]:
P0 = np.array([1, 1, 0])

1. Probando solo con matrices de rotación en 3D

In [ ]:
#Matriz de rotacion 3D sobre el eje x
R_x = Matrix([[1, 0, 0], [0, cos(theta), -sin(theta)], [0, sin(theta), cos(theta)]])
R_x

⎡1    0        0   ⎤
⎢                  ⎥
⎢0  cos(θ)  -sin(θ)⎥
⎢                  ⎥
⎣0  sin(θ)  cos(θ) ⎦

In [ ]:
#Matriz de rotacion 3D sobre el eje y
R_y = Matrix([[cos(theta), 0, sin(theta)], [0, 1, 0], [-sin(theta), 0, cos(theta)]])
R_y

⎡cos(θ)   0  sin(θ)⎤
⎢                  ⎥
⎢   0     1    0   ⎥
⎢                  ⎥
⎣-sin(θ)  0  cos(θ)⎦

In [ ]:
theta_val = np.pi/9 # 20 grados en radianes
R_x_p0 = np.array(R_x.subs({theta: theta_val})).astype(np.float64) #Se convierte theta simbolico a un valor concreto Rx
R_y_p0 = np.array(R_y.subs({theta: theta_val})).astype(np.float64) #Se convierte theta simbolico a un valor concreto Ry

P0_rotado_x = np.dot(R_x_p0, P0) #Producto punto entre la matrix de rotación y el vector de posición del punto
P0_rotado_y = np.dot(R_y_p0, P0_rotado_x) #Producto punto entre la matrix de rotación y el vector de posición del punto

print(P0_rotado_y)

[ 1.0566704   0.93969262 -0.02062634]


2. Ahora probamos con la composición de matrices homogeneas

In [ ]:
#Se convierte el punto 3D a un punto de coordenadas homogeneas

P0_homogeneo = np.append(P0, 1)
P0_homogeneo = np.reshape(P0_homogeneo, (4, 1))
print(P0)
print(P0_homogeneo)

[1 1 0]
[[1]
 [1]
 [0]
 [1]]


In [ ]:
#Se realiza la composición de las matrices homogeneas para x y y
Hxy = H_y@H_x
Hxy

⎡cos(θ)   sin(φ)⋅sin(θ)  sin(θ)⋅cos(φ)  0⎤
⎢                                        ⎥
⎢   0        cos(φ)         -sin(φ)     0⎥
⎢                                        ⎥
⎢-sin(θ)  sin(φ)⋅cos(θ)  cos(φ)⋅cos(θ)  0⎥
⎢                                        ⎥
⎣   0           0              0        1⎦

In [ ]:
theta_val = np.pi/9 # 20 grados en radianes
phi_val = np.pi/9 # 20 grados en radianes

Hxy_p0 = np.array(Hxy.subs({phi: phi_val, theta: theta_val})).astype(np.float64) #Se convierte theta simbolico a un valor concreto Rx
Hxy_p0

array([[ 0.93969262,  0.11697778,  0.3213938 ,  0.        ],
       [ 0.        ,  0.93969262, -0.34202014,  0.        ],
       [-0.34202014,  0.3213938 ,  0.88302222,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:
P0_rotado_Hxy = np.dot(Hxy_p0, P0_homogeneo)
P0_rotado_Hxy

array([[ 1.0566704 ],
       [ 0.93969262],
       [-0.02062634],
       [ 1.        ]])

# **Actividad**

* Calcule las siguientes matrices homogeneas

In [ ]:
from IPython.display import Image

Image(url='1.png')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful

## Donde:

In [ ]:
Image(url='2.png')

# **Resultados aquí debajo**

#**GRUPO 6**
-- Leiser Angarita --
-- Elimelec Ruiz --
-- Aldair Sierra --

# **PUNTO 1**

In [ ]:
H = H_z@H_y@H_x
theta_val = np.pi*56/180
phi_val = np.pi*2/180
psi_val = np.pi*53/180

Hzyx_p0 = np.array(H.subs({phi: phi_val, theta: theta_val, psi:psi_val})).astype(np.float64)

Hzyx_p0

array([[ 0.33653069, -0.78073669,  0.52649531,  0.        ],
       [ 0.44659131,  0.62455533,  0.64069247,  0.        ],
       [-0.82903757,  0.01951555,  0.55885226,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:
np.dot(Hzyx_p0, P0_homogeneo)

array([[-0.444206  ],
       [ 1.07114664],
       [-0.80952202],
       [ 1.        ]])

# **PUNTO 2**

In [ ]:
## Definimos las variables tx, ty y tz. ##

tx = symbols("tx",  real=True)
ty = symbols("ty",  real=True)
tz = symbols("tz",  real=True)

## Definimos la matriz H_y. ##

H_y = Matrix([[cos(theta), 0, sin(theta), tx*cos(theta) + tz*sin(theta)], [0, 1, 0, ty], [-sin(theta), 0, cos(theta), tz*cos(theta) - tx*sin(theta)], [0, 0, 0, 1]])

H_y


⎡cos(θ)   0  sin(θ)  tx⋅cos(θ) + tz⋅sin(θ) ⎤
⎢                                          ⎥
⎢   0     1    0               ty          ⎥
⎢                                          ⎥
⎢-sin(θ)  0  cos(θ)  -tx⋅sin(θ) + tz⋅cos(θ)⎥
⎢                                          ⎥
⎣   0     0    0               1           ⎦

In [ ]:
## Definimos la matriz H_y. ##

H_y = Matrix([[cos(theta), 0, sin(theta), tx*cos(theta) + tz*sin(theta)], [0, 1, 0, ty], [-sin(theta), 0, cos(theta), tz*cos(theta) - tx*sin(theta)], [0, 0, 0, 1]])

H_y

tx_val = 3
ty_val = 0
tz_val = 0
theta_val = np.pi*6/180

H_0 = np.array(H_y.subs({theta: theta_val, tx: tx_val, ty: ty_val, tz:tz_val})).astype(np.float64)

H_0



array([[ 0.9945219 ,  0.        ,  0.10452846,  2.98356569],
       [ 0.        ,  1.        ,  0.        ,  0.        ],
       [-0.10452846,  0.        ,  0.9945219 , -0.31358539],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:
## Definimos la matriz H_x. ##

H_x = Matrix([[1, 0, 0, 0], [0, cos(phi), -sin(phi), 0], [0, sin(phi), cos(phi), 0], [0, 0, 0, 1]])
H_x
phi_val = np.pi*2/180

H_1 = np.array(H_x.subs({phi: phi_val,})).astype(np.float64) #Se convierte phi.

H_1


array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.99939083, -0.0348995 ,  0.        ],
       [ 0.        ,  0.0348995 ,  0.99939083,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:
## Definimos la matriz H_y2. ##
H_y2 = Matrix([[cos(theta), 0, sin(theta), tx*cos(theta) + tz*sin(theta)], [0, 1, 0, ty], [-sin(theta), 0, cos(theta), tz*cos(theta) - tx*sin(theta)], [0, 0, 0, 1]])
H_y2
tx_val = 1
ty_val = 1
tz_val = 0
theta_val = np.pi*-6/180

H_2 = np.array(H_y2.subs({theta: theta_val, tx: tx_val, ty: ty_val, tz:tz_val})).astype(np.float64)

H_2

array([[ 0.9945219 ,  0.        , -0.10452846,  0.9945219 ],
       [ 0.        ,  1.        ,  0.        ,  1.        ],
       [ 0.10452846,  0.        ,  0.9945219 ,  0.10452846],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:
# Calculamos la matriz compuesta H multiplicandolas matrices H_0, H_1 y H_2 en el orden puesto. #
# Luego le aplicamos esta transformación al punto P0_homogeneo.

H = H_0@H_1@H_2
H
np.dot(H, P0_homogeneo)

array([[ 4.99084836],
       [ 1.99148567],
       [-0.24429542],
       [ 1.        ]])

# **PUNTO 3**

In [ ]:
## Definimos las variables tx, ty y tz. ##
## tx: en eje X.
## ty: en eje Y.
## tz: en eje Z.

tx = symbols("tx",  real=True)
ty = symbols("ty",  real=True)
tz = symbols("tz",  real=True)

In [ ]:

## Definimos la matriz H_z para una rotación en el eje Z ##

H_z = Matrix([[cos(psi), -sin(psi), 0, tx], [sin(psi), cos(psi), 0, ty], [0, 0, 1, tz], [0, 0, 0, 1] ])

H_z

tx_val = 3
ty_val = 0
tz_val = 0
psi_val = np.pi*53/180

H_1 = np.array(H_z.subs({psi: psi_val, tx: tx_val, ty: ty_val, tz:tz_val})).astype(np.float64)

H_1

array([[ 0.60181502, -0.79863551,  0.        ,  3.        ],
       [ 0.79863551,  0.60181502,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:

## Definimos la matriz H_y para una rotación en el eje Y ##

H_y = Matrix([[cos(theta), 0, sin(theta), 0], [0, 1, 0, 0], [-sin(theta), 0, cos(theta), 0], [0, 0, 0, 1]])

H_y

theta_val = np.pi*56/180

H_2 = np.array(H_y.subs({theta: theta_val,})).astype(np.float64) #Se convierte theta.

H_2

array([[ 0.5591929 ,  0.        ,  0.82903757,  0.        ],
       [ 0.        ,  1.        ,  0.        ,  0.        ],
       [-0.82903757,  0.        ,  0.5591929 ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:

## Definimos la matriz H_t2 y despues se evalúa como una matriz numérica. ##

t2 = [1, 1, 0]
H_t2 = Matrix([[1, 0, 0, t2[0]], [0, 1, 0, t2[1]], [0, 0, 1, t2[2]], [0, 0, 0, 1]])

H_t2

H_3 = np.array(H_t2.subs({})).astype(np.float64)

H_3

array([[1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:

## Definimos la matriz H_z para una rotación en el eje Z ##

H_z = Matrix([[cos(psi), -sin(psi), 0, 0], [sin(psi), cos(psi), 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])

H_z

psi_val = np.pi*53/180

H_4 = np.array(H_z.subs({psi: psi_val,})).astype(np.float64) #Se convierte psi.

H_4

array([[ 0.60181502, -0.79863551,  0.        ,  0.        ],
       [ 0.79863551,  0.60181502,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:

## Calculamos la matriz H como el producto de múltiples matrices de transformación homogéneas ##
# y luego la aplicamos a un punto en coordenadas homogéneas.

H = H_1@H_2@H_3@H_4

H

np.dot(H, P0_homogeneo)

array([[ 1.35320952],
       [ 1.80332018],
       [-0.66586599],
       [ 1.        ]])

# **PUNTO 4**

In [ ]:

## Definimos las variables simbólicas para representar los desplazamientos en los ejes X, Y y Z. ##
## tx:  en eje X.
## ty:  en eje Y.
## tz:  en eje Z.

tx = symbols("tx",  real=True)
ty = symbols("ty",  real=True)
tz = symbols("tz",  real=True)


In [ ]:

## Definimos la matriz H_y para una rotación en el eje Y. ##

H_y = Matrix([[cos(theta), 0, sin(theta), 0], [0, 1, 0, 0], [-sin(theta), 0, cos(theta), 0], [0, 0, 0, 1]])

H_y

theta_val = np.pi*56/180

H_1 = np.array(H_y.subs({theta: theta_val})).astype(np.float64) #Se convierte psi.

H_1

array([[ 0.5591929 ,  0.        ,  0.82903757,  0.        ],
       [ 0.        ,  1.        ,  0.        ,  0.        ],
       [-0.82903757,  0.        ,  0.5591929 ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:

## Definimos la matriz H_z para una rotación en el eje Z ##

H_z = Matrix([[cos(psi), -sin(psi), 0, tx], [sin(psi), cos(psi), 0, ty], [0, 0, 1, tz], [0, 0, 0, 1]])

H_z

⎡cos(ψ)  -sin(ψ)  0  tx⎤
⎢                      ⎥
⎢sin(ψ)  cos(ψ)   0  ty⎥
⎢                      ⎥
⎢  0        0     1  tz⎥
⎢                      ⎥
⎣  0        0     0  1 ⎦

In [ ]:

## Asignamos valores a las variables tx, ty, tz, y al ángulo de rotación psi para evaluar la matriz H_z. ##

tx_val = 3
ty_val = 0
tz_val = 0

psi_val = np.pi*11/180


H_2 = np.array(H_z.subs({tx: tx_val, ty: ty_val, tz: tz_val, psi: psi_val,})).astype(np.float64) #Se convierte psi.

H_2

array([[ 0.98162718, -0.190809  ,  0.        ,  3.        ],
       [ 0.190809  ,  0.98162718,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:

## Definimos la matriz H_z para una rotación alrededor del eje Z sin traslación. ##

H_z = Matrix([[cos(psi), -sin(psi), 0, 0], [sin(psi), cos(psi), 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])

H_z

⎡cos(ψ)  -sin(ψ)  0  0⎤
⎢                     ⎥
⎢sin(ψ)  cos(ψ)   0  0⎥
⎢                     ⎥
⎢  0        0     1  0⎥
⎢                     ⎥
⎣  0        0     0  1⎦

In [ ]:

## Sustituir el valor del ángulo psi en la matriz H_z y la convierte en una matriz numérica. ##

psi_val = np.pi*-3/180

H_3 = np.array(H_z.subs({psi: psi_val,})).astype(np.float64) #Se convierte psi.

H_3

array([[ 0.99862953,  0.05233596,  0.        ,  0.        ],
       [-0.05233596,  0.99862953,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:

## Definimos la matriz H_x para una rotación alrededor del eje X y la evalúa con un valor específico de phi ##

H_x = Matrix([[1, 0, 0, 0], [0, cos(phi), -sin(phi), 0], [0, sin(phi), cos(phi), 0], [0, 0, 0, 1]])

H_x

phi_val = np.pi*2/180

H_4 = np.array(H_x.subs({phi: phi_val,})).astype(np.float64) #Se convierte phi.

H_4


array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.99939083, -0.0348995 ,  0.        ],
       [ 0.        ,  0.0348995 ,  0.99939083,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:

## Definimos la matriz H_z para una rotación alrededor del eje Z sin traslación. ##

H_z = Matrix([[cos(psi), -sin(psi), 0, 0], [sin(psi), cos(psi), 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])

H_z

⎡cos(ψ)  -sin(ψ)  0  0⎤
⎢                     ⎥
⎢sin(ψ)  cos(ψ)   0  0⎥
⎢                     ⎥
⎢  0        0     1  0⎥
⎢                     ⎥
⎣  0        0     0  1⎦

In [ ]:

## Sustituir el valor del ángulo psi en la matriz H_z y convertirla a tipo float64. ##

psi_val = np.pi*278/180

H_5 = np.array(H_z.subs({psi: psi_val,})).astype(np.float64) #Se convierte psi.

H_5

array([[ 0.1391731 ,  0.99026807,  0.        ,  0.        ],
       [-0.99026807,  0.1391731 ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:

## Calculamos la matriz H y la aplicamos a un punto homogéneo. ##

H = H_1@H_2@H_3@H_4@H_5

H

np.dot(H, P0_homogeneo)

array([[ 2.34457881],
       [-0.68511092],
       [-3.52909827],
       [ 1.        ]])