# **Matrices Homogeneas en un espacio tridimensional**

In [1]:
import numpy as np
from sympy import*
init_printing()

### Declaración de variables simbolicas

In [31]:
## Variables Simbolicas
theta = symbols("theta",  real=True)
phi = symbols("phi",  real=True)
psi = symbols("psi",  real=True)
tx  = symbols("tx", real=True)
ty = symbols("ty", real=True)
tz = symbols("ty", real=True)


### Rotacion eje x

In [3]:
H_x = Matrix([[1, 0, 0, 0], [0, cos(phi), -sin(phi), 0], [0, sin(phi), cos(phi), 0], [0, 0, 0, 1]])
H_x

⎡1    0        0     0⎤
⎢                     ⎥
⎢0  cos(φ)  -sin(φ)  0⎥
⎢                     ⎥
⎢0  sin(φ)  cos(φ)   0⎥
⎢                     ⎥
⎣0    0        0     1⎦

### Rotacion eje y

In [4]:
H_y = Matrix([[cos(theta), 0, sin(theta), 0], [0, 1, 0, 0], [-sin(theta), 0, cos(theta), 0], [0, 0, 0, 1]])
H_y


⎡cos(θ)   0  sin(θ)  0⎤
⎢                     ⎥
⎢   0     1    0     0⎥
⎢                     ⎥
⎢-sin(θ)  0  cos(θ)  0⎥
⎢                     ⎥
⎣   0     0    0     1⎦

### Rotacion eje z

In [5]:
H_z = Matrix([[cos(psi), -sin(psi), 0, 0], [sin(psi), cos(psi), 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
H_z

⎡cos(ψ)  -sin(ψ)  0  0⎤
⎢                     ⎥
⎢sin(ψ)  cos(ψ)   0  0⎥
⎢                     ⎥
⎢  0        0     1  0⎥
⎢                     ⎥
⎣  0        0     0  1⎦

composicion de rotacion de matrices  para transaciones

 traslacion  de X

In [6]:
H_tx = Matrix([[1, 0, 0, tx], [0, cos(phi), -sin(phi), ty], [0, sin(phi), cos(phi), tz], [0, 0, 0, 1]])


H_tx

⎡1    0        0     tx⎤
⎢                      ⎥
⎢0  cos(φ)  -sin(φ)  ty⎥
⎢                      ⎥
⎢0  sin(φ)  cos(φ)   ty⎥
⎢                      ⎥
⎣0    0        0     1 ⎦

traslacion Y

In [7]:
H_ty = Matrix([[cos(theta), 0, sin(theta), tx], [0, 1, 0, ty], [-sin(theta), 0, cos(theta), tz], [0, 0, 0, 1]])
H_ty


⎡cos(θ)   0  sin(θ)  tx⎤
⎢                      ⎥
⎢   0     1    0     ty⎥
⎢                      ⎥
⎢-sin(θ)  0  cos(θ)  ty⎥
⎢                      ⎥
⎣   0     0    0     1 ⎦

traslacion  Z

In [8]:
H_tz = Matrix([[cos(psi), -sin(psi), 0, tx], [sin(psi), cos(psi), 0, ty], [0, 0, 1, tz], [0, 0, 0, 1]])
H_tz

⎡cos(ψ)  -sin(ψ)  0  tx⎤
⎢                      ⎥
⎢sin(ψ)  cos(ψ)   0  ty⎥
⎢                      ⎥
⎢  0        0     1  ty⎥
⎢                      ⎥
⎣  0        0     0  1 ⎦

### Composicion de Matrices Homogeneas

Probando la conmutatividad de las matrices homogeneas

In [9]:
H = H_z@H_y@H_x
H

⎡cos(ψ)⋅cos(θ)  sin(φ)⋅sin(θ)⋅cos(ψ) - sin(ψ)⋅cos(φ)  sin(φ)⋅sin(ψ) + sin(θ)⋅cos(φ)⋅cos(ψ)   0⎤
⎢                                                                                             ⎥
⎢sin(ψ)⋅cos(θ)  sin(φ)⋅sin(ψ)⋅sin(θ) + cos(φ)⋅cos(ψ)  -sin(φ)⋅cos(ψ) + sin(ψ)⋅sin(θ)⋅cos(φ)  0⎥
⎢                                                                                             ⎥
⎢   -sin(θ)                sin(φ)⋅cos(θ)                          cos(φ)⋅cos(θ)              0⎥
⎢                                                                                             ⎥
⎣      0                         0                                      0                    1⎦

In [10]:
H = H_x@H_y@H_z
H

⎡           cos(ψ)⋅cos(θ)                         -sin(ψ)⋅cos(θ)                  sin(θ)      0⎤
⎢                                                                                              ⎥
⎢sin(φ)⋅sin(θ)⋅cos(ψ) + sin(ψ)⋅cos(φ)  -sin(φ)⋅sin(ψ)⋅sin(θ) + cos(φ)⋅cos(ψ)  -sin(φ)⋅cos(θ)  0⎥
⎢                                                                                              ⎥
⎢sin(φ)⋅sin(ψ) - sin(θ)⋅cos(φ)⋅cos(ψ)  sin(φ)⋅cos(ψ) + sin(ψ)⋅sin(θ)⋅cos(φ)   cos(φ)⋅cos(θ)   0⎥
⎢                                                                                              ⎥
⎣                 0                                      0                          0         1⎦

In [11]:
H = H_ty@H_x@H_ty
H

⎡          2                2                                                                      ↪
⎢     - sin (θ)⋅cos(φ) + cos (θ)        sin(φ)⋅sin(θ)  sin(θ)⋅cos(φ)⋅cos(θ) + sin(θ)⋅cos(θ)  tx⋅co ↪
⎢                                                                                                  ↪
⎢            sin(φ)⋅sin(θ)                 cos(φ)                 -sin(φ)⋅cos(θ)                   ↪
⎢                                                                                                  ↪
⎢                                                                2                2                ↪
⎢-sin(θ)⋅cos(φ)⋅cos(θ) - sin(θ)⋅cos(θ)  sin(φ)⋅cos(θ)       - sin (θ) + cos(φ)⋅cos (θ)       -tx⋅s ↪
⎢                                                                                                  ↪
⎣                  0                          0                         0                          ↪

↪                                                 ⎤
↪ s(θ) + tx + ty⋅sin(φ)⋅sin(θ) + ty⋅si

# **Experimento 1**
#### Comprobar que una secuencia de rotaciones produce el mismo resultado que una composición de matrices homogeneas

In [12]:
P0 = np.array([1, 1, 0])

1. Probando solo con matrices de rotación en 3D

In [13]:
#Matriz de rotacion 3D sobre el eje x
R_x = Matrix([[1, 0, 0], [0, cos(theta), -sin(theta)], [0, sin(theta), cos(theta)]])
R_x

⎡1    0        0   ⎤
⎢                  ⎥
⎢0  cos(θ)  -sin(θ)⎥
⎢                  ⎥
⎣0  sin(θ)  cos(θ) ⎦

In [14]:
#Matriz de rotacion 3D sobre el eje y
R_y = Matrix([[cos(theta), 0, sin(theta)], [0, 1, 0], [-sin(theta), 0, cos(theta)]])
R_y

⎡cos(θ)   0  sin(θ)⎤
⎢                  ⎥
⎢   0     1    0   ⎥
⎢                  ⎥
⎣-sin(θ)  0  cos(θ)⎦

In [15]:
theta_val = np.pi/9 # 20 grados en radianes
R_x_p0 = np.array(R_x.subs({theta: theta_val})).astype(np.float64) #Se convierte theta simbolico a un valor concreto Rx
R_y_p0 = np.array(R_y.subs({theta: theta_val})).astype(np.float64) #Se convierte theta simbolico a un valor concreto Ry

P0_rotado_x = np.dot(R_x_p0, P0) #Producto punto entre la matrix de rotación y el vector de posición del punto
P0_rotado_y = np.dot(R_y_p0, P0_rotado_x) #Producto punto entre la matrix de rotación y el vector de posición del punto

print(P0_rotado_y)

[ 1.0566704   0.93969262 -0.02062634]


2. Ahora probamos con la composición de matrices homogeneas

In [16]:
#Se convierte el punto 3D a un punto de coordenadas homogeneas

P0_homogeneo = np.append(P0, 1)
P0_homogeneo = np.reshape(P0_homogeneo, (4, 1))
print(P0)
print(P0_homogeneo)

[1 1 0]
[[1]
 [1]
 [0]
 [1]]


In [17]:
#Se realiza la composición de las matrices homogeneas para x y y
Hxy = H_y@H_x
Hxy

⎡cos(θ)   sin(φ)⋅sin(θ)  sin(θ)⋅cos(φ)  0⎤
⎢                                        ⎥
⎢   0        cos(φ)         -sin(φ)     0⎥
⎢                                        ⎥
⎢-sin(θ)  sin(φ)⋅cos(θ)  cos(φ)⋅cos(θ)  0⎥
⎢                                        ⎥
⎣   0           0              0        1⎦

In [18]:
theta_val = np.pi/9 # 20 grados en radianes
phi_val = np.pi/9 # 20 grados en radianes

Hxy_p0 = np.array(Hxy.subs({phi: phi_val, theta: theta_val})).astype(np.float64) #Se convierte theta simbolico a un valor concreto Rx
Hxy_p0

array([[ 0.93969262,  0.11697778,  0.3213938 ,  0.        ],
       [ 0.        ,  0.93969262, -0.34202014,  0.        ],
       [-0.34202014,  0.3213938 ,  0.88302222,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [19]:
P0_rotado_Hxy = np.dot(Hxy_p0, P0_homogeneo)
P0_rotado_Hxy

array([[ 1.0566704 ],
       [ 0.93969262],
       [-0.02062634],
       [ 1.        ]])

# **Actividad**

* Calcule las siguientes matrices homogeneas

In [20]:
from IPython.display import Image

Image(url='1.png')

## Donde:

In [21]:
Image(url='2.png')

# **Resultados aquí debajo**

##ejercicio 1


In [22]:
H = H_z@H_y@H_x
theta_val = np.pi*56/180 # 20 grados en radianes
phi_val = np.pi*2/180
psi_val = np.pi*53/180

Hzyx = np.array(H.subs({phi: phi_val, theta: theta_val, psi: psi_val})).astype(np.float64) #Se convierte theta simbolico a un valor concreto Rx

Hzyx

array([[ 0.33653069, -0.78073669,  0.52649531,  0.        ],
       [ 0.44659131,  0.62455533,  0.64069247,  0.        ],
       [-0.82903757,  0.01951555,  0.55885226,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [23]:
np.dot(Hzyx, P0_homogeneo)

array([[-0.444206  ],
       [ 1.07114664],
       [-0.80952202],
       [ 1.        ]])

##ejercicio2

In [37]:
H = H_y@H_x@H_y
t1_val=[3,0,0]
theta1_val = np.pi*6/180
phi_val = np.pi*2/180
t2_val =np.pi*1,1,0/180
theta2_val= np.pi*-6/180

Htyxty = np.array(H.subs({ty: t1_val,theta: theta1_val, phi: phi_val, theta: theta2_val,tz: t2_val})).astype(np.float64) #Se convierte theta simbolico a un valor concreto Rx

Htyxty

array([[ 0.97815426, -0.00364799, -0.20784836,  0.        ],
       [-0.00364799,  0.99939083, -0.03470831,  0.        ],
       [ 0.20784836,  0.03470831,  0.97754508,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [25]:
np.dot(Htyxty, P0_homogeneo)

array([[0.97450627],
       [0.99574284],
       [0.24255668],
       [1.        ]])

##ejercicio 3

In [26]:
H = H_z@H_y@H_z
psi_val = np.pi*53/180 # 20 grados en radianes
t1_val =np.pi*3,0,0/180,
theta_val = np.pi*56/180
t2_val =np.pi*1,1,0/180
psi_val = np.pi*53/180

Hzytzz = np.array(H.subs({psi: psi_val, tz: t1_val, theta: theta_val, tz: t2_val,})).astype(np.float64) #Se convierte theta simbolico a un valor concreto Rx

Hzytzz

array([[-0.43528945, -0.74939621,  0.49892727,  0.        ],
       [ 0.74939621,  0.00551764,  0.66209884,  0.        ],
       [-0.49892727,  0.66209884,  0.5591929 ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [27]:
np.dot(Hzytzz, P0_homogeneo)

array([[-1.18468566],
       [ 0.75491385],
       [ 0.16317158],
       [ 1.        ]])

##ejercicio 4

In [28]:
H = H_y@H_z@H_z@H_x@H_z
theta_val = np.pi*56/180 # 20 grados en radianes
psi1_val = np.pi*11/180
t1_val =np.pi*3,0,0/180
psi2_val = np.pi*-3/180
phi_val = np.pi*2/180
psi3_val = np.pi*278/180

Hytzzxz = np.array(H.subs({theta: theta_val, phi: psi1_val, tz: t1_val, psi: psi2_val, phi: psi_val, psi: psi3_val })).astype(np.float64) #Se convierte theta simbolico a un valor concreto Rx

Hytzzxz

array([[-0.82232285, -0.4272434 ,  0.37583002,  0.        ],
       [ 0.53451049, -0.35346675,  0.76769772,  0.        ],
       [-0.19515037,  0.83218047,  0.51902986,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [29]:
np.dot(Hytzzxz, P0_homogeneo)

array([[-1.24956625],
       [ 0.18104373],
       [ 0.6370301 ],
       [ 1.        ]])