# **Matrices Homogeneas en un espacio tridimensional**

**Docente:** PhD Jorge Rudas

**Diseño de prototipos - 2025 I**

**INFOTEP**

In [2]:
import numpy as np
from sympy import*
init_printing()

### Declaración de variables simbolicas

In [3]:
## Variables Simbolicas
theta = symbols("theta",  real=True)
phi = symbols("phi",  real=True)
psi = symbols("psi",  real=True)

### Rotacion eje x

In [4]:
H_x = Matrix([[1, 0, 0, 0], [0, cos(phi), -sin(phi), 0], [0, sin(phi), cos(phi), 0], [0, 0, 0, 1]])
H_x

⎡1    0        0     0⎤
⎢                     ⎥
⎢0  cos(φ)  -sin(φ)  0⎥
⎢                     ⎥
⎢0  sin(φ)  cos(φ)   0⎥
⎢                     ⎥
⎣0    0        0     1⎦

### Rotacion eje y

In [5]:
H_y = Matrix([[cos(theta), 0, sin(theta), 0], [0, 1, 0, 0], [-sin(theta), 0, cos(theta), 0], [0, 0, 0, 1]])
H_y


⎡cos(θ)   0  sin(θ)  0⎤
⎢                     ⎥
⎢   0     1    0     0⎥
⎢                     ⎥
⎢-sin(θ)  0  cos(θ)  0⎥
⎢                     ⎥
⎣   0     0    0     1⎦

### Rotacion eje z

In [6]:
H_z = Matrix([[cos(psi), -sin(psi), 0, 0], [sin(psi), cos(psi), 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
H_z

⎡cos(ψ)  -sin(ψ)  0  0⎤
⎢                     ⎥
⎢sin(ψ)  cos(ψ)   0  0⎥
⎢                     ⎥
⎢  0        0     1  0⎥
⎢                     ⎥
⎣  0        0     0  1⎦

### Composicion de Matrices Homogeneas

Probando la conmutatividad de las matrices homogeneas

In [7]:
H = H_z@H_y@H_x
H

⎡cos(ψ)⋅cos(θ)  sin(φ)⋅sin(θ)⋅cos(ψ) - sin(ψ)⋅cos(φ)  sin(φ)⋅sin(ψ) + sin(θ)⋅cos(φ)⋅cos(ψ)   0⎤
⎢                                                                                             ⎥
⎢sin(ψ)⋅cos(θ)  sin(φ)⋅sin(ψ)⋅sin(θ) + cos(φ)⋅cos(ψ)  -sin(φ)⋅cos(ψ) + sin(ψ)⋅sin(θ)⋅cos(φ)  0⎥
⎢                                                                                             ⎥
⎢   -sin(θ)                sin(φ)⋅cos(θ)                          cos(φ)⋅cos(θ)              0⎥
⎢                                                                                             ⎥
⎣      0                         0                                      0                    1⎦

In [8]:
H = H_x@H_y@H_z
H

⎡           cos(ψ)⋅cos(θ)                         -sin(ψ)⋅cos(θ)                  sin(θ)      0⎤
⎢                                                                                              ⎥
⎢sin(φ)⋅sin(θ)⋅cos(ψ) + sin(ψ)⋅cos(φ)  -sin(φ)⋅sin(ψ)⋅sin(θ) + cos(φ)⋅cos(ψ)  -sin(φ)⋅cos(θ)  0⎥
⎢                                                                                              ⎥
⎢sin(φ)⋅sin(ψ) - sin(θ)⋅cos(φ)⋅cos(ψ)  sin(φ)⋅cos(ψ) + sin(ψ)⋅sin(θ)⋅cos(φ)   cos(φ)⋅cos(θ)   0⎥
⎢                                                                                              ⎥
⎣                 0                                      0                          0         1⎦

# **Experimento 1**
#### Comprobar que una secuencia de rotaciones produce el mismo resultado que una composición de matrices homogeneas

In [9]:
P0 = np.array([1, 1, 0])

1. Probando solo con matrices de rotación en 3D

In [10]:
#Matriz de rotacion 3D sobre el eje x
R_x = Matrix([[1, 0, 0], [0, cos(theta), -sin(theta)], [0, sin(theta), cos(theta)]])
R_x

⎡1    0        0   ⎤
⎢                  ⎥
⎢0  cos(θ)  -sin(θ)⎥
⎢                  ⎥
⎣0  sin(θ)  cos(θ) ⎦

In [11]:
#Matriz de rotacion 3D sobre el eje y
R_y = Matrix([[cos(theta), 0, sin(theta)], [0, 1, 0], [-sin(theta), 0, cos(theta)]])
R_y

⎡cos(θ)   0  sin(θ)⎤
⎢                  ⎥
⎢   0     1    0   ⎥
⎢                  ⎥
⎣-sin(θ)  0  cos(θ)⎦

In [12]:
theta_val = np.pi/9 # 20 grados en radianes
R_x_p0 = np.array(R_x.subs({theta: theta_val})).astype(np.float64) #Se convierte theta simbolico a un valor concreto Rx
R_y_p0 = np.array(R_y.subs({theta: theta_val})).astype(np.float64) #Se convierte theta simbolico a un valor concreto Ry

P0_rotado_x = np.dot(R_x_p0, P0) #Producto punto entre la matrix de rotación y el vector de posición del punto
P0_rotado_y = np.dot(R_y_p0, P0_rotado_x) #Producto punto entre la matrix de rotación y el vector de posición del punto

print(P0_rotado_y)

[ 1.0566704   0.93969262 -0.02062634]


2. Ahora probamos con la composición de matrices homogeneas

In [13]:
#Se convierte el punto 3D a un punto de coordenadas homogeneas

P0_homogeneo = np.append(P0, 1)
P0_homogeneo = np.reshape(P0_homogeneo, (4, 1))
print(P0)
print(P0_homogeneo)

[1 1 0]
[[1]
 [1]
 [0]
 [1]]


In [14]:
#Se realiza la composición de las matrices homogeneas para x y y
Hxy = H_y@H_x
Hxy

⎡cos(θ)   sin(φ)⋅sin(θ)  sin(θ)⋅cos(φ)  0⎤
⎢                                        ⎥
⎢   0        cos(φ)         -sin(φ)     0⎥
⎢                                        ⎥
⎢-sin(θ)  sin(φ)⋅cos(θ)  cos(φ)⋅cos(θ)  0⎥
⎢                                        ⎥
⎣   0           0              0        1⎦

In [15]:
theta_val = np.pi/9 # 20 grados en radianes
phi_val = np.pi/9 # 20 grados en radianes

Hxy_p0 = np.array(Hxy.subs({phi: phi_val, theta: theta_val})).astype(np.float64) #Se convierte theta simbolico a un valor concreto Rx
Hxy_p0

array([[ 0.93969262,  0.11697778,  0.3213938 ,  0.        ],
       [ 0.        ,  0.93969262, -0.34202014,  0.        ],
       [-0.34202014,  0.3213938 ,  0.88302222,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [16]:
P0_rotado_Hxy = np.dot(Hxy_p0, P0_homogeneo)
P0_rotado_Hxy

array([[ 1.0566704 ],
       [ 0.93969262],
       [-0.02062634],
       [ 1.        ]])

# **Actividad**

* Calcule las siguientes matrices homogeneas

In [17]:
from IPython.display import Image

Image(url='/content/1.png')

## Donde:

In [18]:
Image(url='/content/2.png')

# **Resultados aquí debajo**

**1).  Ψ=53°, Φ=2, θ=56°**

In [19]:
Hzyx = H_z@H_y@H_x

theta_val = np.pi*56/180
phi_val = np.pi*2/180
psi_val = np.pi*53/180

Hzyx_p0 = np.array(Hzyx.subs({phi: phi_val, theta: theta_val, psi: psi_val})).astype(np.float64)

print(Hzyx_p0)
print()
np.dot(Hzyx_p0, P0_homogeneo)

[[ 0.33653069 -0.78073669  0.52649531  0.        ]
 [ 0.44659131  0.62455533  0.64069247  0.        ]
 [-0.82903757  0.01951555  0.55885226  0.        ]
 [ 0.          0.          0.          1.        ]]



array([[-0.444206  ],
       [ 1.07114664],
       [-0.80952202],
       [ 1.        ]])

**2). θ=6°, Φ=2, θ2=-6°, t1 = [3, 0, 0], t2= [1, 1, 0]**



In [20]:
theta2 = symbols("theta2", real=True)
theta_val = np.pi*6/180
phi_val = np.pi*2/180
theta2_val = np.pi*-6/180

t1 = Matrix([3, 0, 0])
t2 = Matrix([1, 1, 0])

H_y1 = Matrix([[cos(theta), 0, sin(theta), t1[0]*cos(theta)+t1[2]*sin(theta)], [0, 1,  0, t1[1]], [-sin(theta), 0, cos(theta), t1[2]*cos(theta)-t1[0]*sin(theta)], [0, 0, 0, 1] ])
H_y2 = Matrix([[cos(theta2), 0, sin(theta2), t2[0]*cos(theta2)+t2[2]*sin(theta2)], [0, 1,  0, t2[1]],[-sin(theta2), 0, cos(theta2), t2[2]*cos(theta2)-t2[0]*sin(theta2)], [0, 0, 0, 1]])

Hyxy = H_y1@H_x@H_y2
H = np.array(Hyxy.subs({phi: phi_val, theta: theta_val, theta2: theta2_val})).astype(np.float64)

print(H)
print()
np.dot(H, P0_homogeneo)


[[ 9.99993344e-01  3.64799076e-03 -6.33270922e-05  3.98720702e+00]
 [-3.64799076e-03  9.99390827e-01 -3.47083136e-02  9.95742836e-01]
 [-6.33270922e-05  3.47083136e-02  9.99397483e-01 -2.78940403e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]



array([[ 4.99084836],
       [ 1.99148567],
       [-0.24429542],
       [ 1.        ]])

**3). Ψ=53°, θ=56° t1= [3, 0, 0] t2= [1, 1, 0]**

In [21]:
theta_val = np.pi*56/180
psi_val = np.pi*53/180

t = Matrix([3, 0, 0])
t2 = Matrix([1, 1, 0])


Ht2 = Matrix([[1, 0, 0, t2[0]],[0, 1, 0, t2[1]], [0, 0, 1, t2[2]],[0, 0, 0, 1]])
H_zt = Matrix([[cos(psi), -sin(psi), 0, t[0]], [sin(psi), cos(psi), 0, t[1]], [0, 0, 1, t[2]], [0, 0, 0, 1]])
H_y = Matrix([[cos(theta), 0, sin(theta),  0], [0, 1, 0, 0], [-sin(theta), 0, cos(theta), 0], [0, 0, 0, 1]])
H_z = Matrix([[cos(psi), -sin(psi), 0, 0], [sin(psi), cos(psi), 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])

Hztytz= H_zt@H_y@Ht2@H_z
H = np.array(Hztytz.subs({ theta: theta_val, psi:psi_val})).astype(np.float64)

print(H)
print()
np.dot(H, P0_homogeneo)



[[-0.43528945 -0.74939621  0.49892727  2.53789518]
 [ 0.74939621  0.00551764  0.66209884  1.04840633]
 [-0.49892727  0.66209884  0.5591929  -0.82903757]
 [ 0.          0.          0.          1.        ]]



array([[ 1.35320952],
       [ 1.80332018],
       [-0.66586599],
       [ 1.        ]])

**4). Ψ1=11°, Ψ2=-3°, Ψ3=278°, Φ=2, θ=56°, t = [3, 0, 0]**

In [27]:
#4
psi1 = symbols("psi1", real=True)
psi2 = symbols("psi2", real=True)
theta_val = np.pi*56/180
phi_val = np.pi*2/180
psi_val = np.pi*11/180
psi_val1 = np.pi*-3/180
psi_val2 = np.pi*278/180

t = Matrix([3, 0, 0])

H_y = Matrix([[cos(theta), 0, sin(theta),  0], [0, 1, 0, 0], [-sin(theta), 0, cos(theta), 0], [0, 0, 0, 1]])
H_zt = Matrix([[cos(psi), -sin(psi), 0, t[0]], [sin(psi), cos(psi), 0, t[1]], [0, 0, 1, t[2]], [0, 0, 0, 1]])
H_z = Matrix([[cos(psi1), -sin(psi1), 0, 0], [sin(psi1), cos(psi1), 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
H_z2 = Matrix([[cos(psi2), -sin(psi2), 0, 0], [sin(psi2), cos(psi2), 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])

Hyzxz2= H_y@H_zt@H_x@H_z@H_z2

H = np.array(Hyzxz2.subs({phi: phi_val, theta: theta_val, psi: psi_val, psi1: psi_val1, psi2: psi_val2})).astype(np.float64)

print(H)
print()
np.dot(H, P0_homogeneo)


[[ 0.12524681  0.54005806  0.83225629  1.67757871]
 [-0.96066599  0.27558524 -0.03425829  0.        ]
 [-0.24785902 -0.79522957  0.55333158 -2.48711272]
 [ 0.          0.          0.          1.        ]]



array([[ 2.34288358],
       [-0.68508075],
       [-3.5302013 ],
       [ 1.        ]])