# **Matrices Homogeneas en un espacio tridimensional**

**Docente:** PhD Jorge Rudas

**Diseño de prototipos - 2025 I**

**INFOTEP**

In [ ]:
import numpy as np
from sympy import*
init_printing()

### Declaración de variables simbolicas

In [ ]:
## Variables Simbolicas
theta = symbols("theta",  real=True)
phi = symbols("phi",  real=True)
psi = symbols("psi",  real=True)

### Rotacion eje x

In [ ]:
H_x = Matrix([[1, 0, 0, 0], [0, cos(phi), -sin(phi), 0], [0, sin(phi), cos(phi), 0], [0, 0, 0, 1]])
H_x

⎡1    0        0     0⎤
⎢                     ⎥
⎢0  cos(φ)  -sin(φ)  0⎥
⎢                     ⎥
⎢0  sin(φ)  cos(φ)   0⎥
⎢                     ⎥
⎣0    0        0     1⎦

### Rotacion eje y

In [ ]:
H_y = Matrix([[cos(theta), 0, sin(theta), 0], [0, 1, 0, 0], [-sin(theta), 0, cos(theta), 0], [0, 0, 0, 1]])
H_y


⎡cos(θ)   0  sin(θ)  0⎤
⎢                     ⎥
⎢   0     1    0     0⎥
⎢                     ⎥
⎢-sin(θ)  0  cos(θ)  0⎥
⎢                     ⎥
⎣   0     0    0     1⎦

### Rotacion eje z

In [ ]:
H_z = Matrix([[cos(psi), -sin(psi), 0, 0], [sin(psi), cos(psi), 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
H_z

⎡cos(ψ)  -sin(ψ)  0  0⎤
⎢                     ⎥
⎢sin(ψ)  cos(ψ)   0  0⎥
⎢                     ⎥
⎢  0        0     1  0⎥
⎢                     ⎥
⎣  0        0     0  1⎦

### Composicion de Matrices Homogeneas

Probando la conmutatividad de las matrices homogeneas

In [ ]:
H = H_z@H_y@H_x
H

⎡cos(ψ)⋅cos(θ)  sin(φ)⋅sin(θ)⋅cos(ψ) - sin(ψ)⋅cos(φ)  sin(φ)⋅sin(ψ) + sin(θ)⋅cos(φ)⋅cos(ψ)   0⎤
⎢                                                                                             ⎥
⎢sin(ψ)⋅cos(θ)  sin(φ)⋅sin(ψ)⋅sin(θ) + cos(φ)⋅cos(ψ)  -sin(φ)⋅cos(ψ) + sin(ψ)⋅sin(θ)⋅cos(φ)  0⎥
⎢                                                                                             ⎥
⎢   -sin(θ)                sin(φ)⋅cos(θ)                          cos(φ)⋅cos(θ)              0⎥
⎢                                                                                             ⎥
⎣      0                         0                                      0                    1⎦

In [ ]:
H = H_x@H_y@H_z
H

⎡           cos(ψ)⋅cos(θ)                         -sin(ψ)⋅cos(θ)                  sin(θ)      0⎤
⎢                                                                                              ⎥
⎢sin(φ)⋅sin(θ)⋅cos(ψ) + sin(ψ)⋅cos(φ)  -sin(φ)⋅sin(ψ)⋅sin(θ) + cos(φ)⋅cos(ψ)  -sin(φ)⋅cos(θ)  0⎥
⎢                                                                                              ⎥
⎢sin(φ)⋅sin(ψ) - sin(θ)⋅cos(φ)⋅cos(ψ)  sin(φ)⋅cos(ψ) + sin(ψ)⋅sin(θ)⋅cos(φ)   cos(φ)⋅cos(θ)   0⎥
⎢                                                                                              ⎥
⎣                 0                                      0                          0         1⎦

# **Experimento 1**
#### Comprobar que una secuencia de rotaciones produce el mismo resultado que una composición de matrices homogeneas

In [ ]:
P0 = np.array([1, 1, 0])

1. Probando solo con matrices de rotación en 3D

In [ ]:
#Matriz de rotacion 3D sobre el eje x
R_x = Matrix([[1, 0, 0], [0, cos(theta), -sin(theta)], [0, sin(theta), cos(theta)]])
R_x

⎡1    0        0   ⎤
⎢                  ⎥
⎢0  cos(θ)  -sin(θ)⎥
⎢                  ⎥
⎣0  sin(θ)  cos(θ) ⎦

In [ ]:
#Matriz de rotacion 3D sobre el eje y
R_y = Matrix([[cos(theta), 0, sin(theta)], [0, 1, 0], [-sin(theta), 0, cos(theta)]])
R_y

⎡cos(θ)   0  sin(θ)⎤
⎢                  ⎥
⎢   0     1    0   ⎥
⎢                  ⎥
⎣-sin(θ)  0  cos(θ)⎦

In [ ]:
theta_val = np.pi/9 # 20 grados en radianes
R_x_p0 = np.array(R_x.subs({theta: theta_val})).astype(np.float64) #Se convierte theta simbolico a un valor concreto Rx
R_y_p0 = np.array(R_y.subs({theta: theta_val})).astype(np.float64) #Se convierte theta simbolico a un valor concreto Ry

P0_rotado_x = np.dot(R_x_p0, P0) #Producto punto entre la matrix de rotación y el vector de posición del punto
P0_rotado_y = np.dot(R_y_p0, P0_rotado_x) #Producto punto entre la matrix de rotación y el vector de posición del punto

print(P0_rotado_y)

[ 1.0566704   0.93969262 -0.02062634]


2. Ahora probamos con la composición de matrices homogeneas

In [ ]:
#Se convierte el punto 3D a un punto de coordenadas homogeneas

P0_homogeneo = np.append(P0, 1)
P0_homogeneo = np.reshape(P0_homogeneo, (4, 1))
print(P0)
print(P0_homogeneo)

[1 1 0]
[[1]
 [1]
 [0]
 [1]]


In [ ]:
#Se realiza la composición de las matrices homogeneas para x y y
Hxy = H_y@H_x
Hxy

⎡cos(θ)   sin(φ)⋅sin(θ)  sin(θ)⋅cos(φ)  0⎤
⎢                                        ⎥
⎢   0        cos(φ)         -sin(φ)     0⎥
⎢                                        ⎥
⎢-sin(θ)  sin(φ)⋅cos(θ)  cos(φ)⋅cos(θ)  0⎥
⎢                                        ⎥
⎣   0           0              0        1⎦

In [ ]:
theta_val = np.pi/9 # 20 grados en radianes
phi_val = np.pi/9 # 20 grados en radianes

Hxy_p0 = np.array(Hxy.subs({phi: phi_val, theta: theta_val})).astype(np.float64) #Se convierte theta simbolico a un valor concreto Rx
Hxy_p0

array([[ 0.93969262,  0.11697778,  0.3213938 ,  0.        ],
       [ 0.        ,  0.93969262, -0.34202014,  0.        ],
       [-0.34202014,  0.3213938 ,  0.88302222,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:
P0_rotado_Hxy = np.dot(Hxy_p0, P0_homogeneo)
P0_rotado_Hxy

array([[ 1.0566704 ],
       [ 0.93969262],
       [-0.02062634],
       [ 1.        ]])

# **Actividad**

* Calcule las siguientes matrices homogeneas

In [ ]:
from IPython.display import Image

Image(url='1.png')

## Donde:

In [ ]:
Image(url='2.png')

# **Resultados aquí debajo**

In [ ]:
H = H_z@H_y@H_x
theta_val = np.pi*56/180 # 20 grados en radianes
phi_val = np.pi*2/180
psi_val = np.pi*53/180

Hzyx = np.array(H.subs({phi: phi_val, theta: theta_val, psi: psi_val})).astype(np.float64) #Se convierte theta simbolico a un valor concreto Rx

Hzyx

array([[ 0.33653069, -0.78073669,  0.52649531,  0.        ],
       [ 0.44659131,  0.62455533,  0.64069247,  0.        ],
       [-0.82903757,  0.01951555,  0.55885226,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:
np.dot(Hzyx, P0_homogeneo)

array([[-0.444206  ],
       [ 1.07114664],
       [-0.80952202],
       [ 1.        ]])

# Actividad 2

In [ ]:
#variables simbolicas
tx = symbols("tx",  real=True)
ty = symbols("ty",  real=True)
tz = symbols("tz",  real=True)


## Matriz de traslación y luego rotación en Y

In [ ]:
# Se añade la matriz de traslación y rotación sobre eje Y
H_ty = Matrix([[cos(theta), 0, sin(theta), tx * cos(theta) + tz * sin(theta)],
                [0, 1, 0, ty],
                  [-sin(theta), 0, cos(theta), tz * cos(theta) - tx * sin(theta)],
                   [0, 0, 0, 1]])
H_ty

⎡cos(θ)   0  sin(θ)  tx⋅cos(θ) + tz⋅sin(θ) ⎤
⎢                                          ⎥
⎢   0     1    0               ty          ⎥
⎢                                          ⎥
⎢-sin(θ)  0  cos(θ)  -tx⋅sin(θ) + tz⋅cos(θ)⎥
⎢                                          ⎥
⎣   0     0    0               1           ⎦

## Calculo de grados en radianes y traslaciones

In [ ]:
#Conversiones a radianes
phi_val = 2 * np.pi / 180
theta1_rad = 6 * np.pi / 180
theta2_rad = -6 * np.pi / 180

# Traslaciones
t1 = [3, 0, 0]
t2 = [1, 1, 0]



## Resultado matriz

In [ ]:
# Se calcula la matriz
H_t1_y = H_ty.subs({theta: theta1_rad, tx: t1[0], ty: t1[1], tz: t1[2]})
H_x_phi = H_x.subs({phi: phi_val})
H_t2_y = H_ty.subs({theta: theta2_rad, tx: t2[0], ty: t2[1], tz: t2[2]})
H_2 = simplify(H_t1_y @ H_x_phi @ H_t2_y)

# Resultado
H_2

⎡0.0109261996330972⋅cos(φ) + 0.989073800366903  0.104528463267653⋅sin(φ)   0.10395584540888⋅cos(φ) ↪
⎢                                                                                                  ↪
⎢          -0.104528463267653⋅sin(φ)                     cos(φ)                     -0.99452189536 ↪
⎢                                                                                                  ↪
⎢ 0.10395584540888⋅cos(φ) - 0.10395584540888    0.994521895368273⋅sin(φ)  0.989073800366903⋅cos(φ) ↪
⎢                                                                                                  ↪
⎣                      0                                   0                                    0  ↪

↪  - 0.10395584540888    0.104528463267653⋅sin(φ) + 0.0109261996330972⋅cos(φ) + 3.97263948647172⎤
↪                                                                                               ⎥
↪ 8273⋅sin(φ)                              -0.104528463267653⋅sin(φ) + cos(φ)                   

# Actividad 3

## Matriz de traslación y rotación en Z

In [ ]:
# Matriz de traslación y rotación sobre Z
H_tz = Matrix([[cos(psi), -sin(psi), 0, tx],
               [sin(psi), cos(psi), 0, ty],
               [0, 0, 1, tz],
               [0, 0, 0, 1]])
H_tz

⎡cos(ψ)  -sin(ψ)  0  tx⎤
⎢                      ⎥
⎢sin(ψ)  cos(ψ)   0  ty⎥
⎢                      ⎥
⎢  0        0     1  tz⎥
⎢                      ⎥
⎣  0        0     0  1 ⎦

## Resultado de la matriz

In [ ]:
# Se calcula la matriz
H_zt1 = H_tz.subs({psi: psi_val, tx: t1[0], ty: t1[1], tz: t1[2]})
H_y_theta = H_y.subs({theta: theta_val})
H_t2_y = H_ty.subs({theta: 0, tx: t2[0], ty: t2[1], tz: t2[2]})
H_z_psi = H_z.subs({psi: psi_val})
H_3 = simplify(H_zt1 @ H_y_theta @ H_t2_y @ H_z_psi)

# Resultado
H_3

⎡-0.277621422995073   -0.958628749863908  0.0629067995414709   2.79988270743898 ⎤
⎢                                                                               ⎥
⎢ 0.958628749863908   -0.272143318363347  0.0834801425762221   1.39607552431269 ⎥
⎢                                                                               ⎥
⎢-0.0629067995414709  0.0834801425762221  0.994521895368273   -0.104528463267653⎥
⎢                                                                               ⎥
⎣         0                   0                   0                   1         ⎦

# Actividad 4

## Calculo de grados en radianes

In [ ]:
# Conversión de grados a radianes
psi1_rad = 11 * np.pi / 180
psi2_rad = -3 * np.pi / 180
psi3_rad = 278 * np.pi / 180

## Resultado de la matriz

In [ ]:
# Se calcula la matriz
H_y_theta = H_y.subs({theta: theta_val})
H_tz1 = H_tz.subs({psi: psi1_rad, tx: t1[0], ty: t1[1], tz: t1[2]})
H_z_psi2 = H_z.subs({psi: psi2_rad})
H_x_phi = H_x.subs({phi: phi_val})
H_z_psi3 = H_z.subs({psi: psi3_rad})
H_4 = simplify(H_y_theta @ H_tz1 @ H_z_psi2 @ H_x_phi @ H_z_psi3)

# Resultado
H_4

⎡ 0.270431401279295    0.956515240502744    0.109295250986011   2.98356568610482 ⎤
⎢                                                                                ⎥
⎢-0.960664322121495    0.275553400402153   -0.0345598571996384          0        ⎥
⎢                                                                                ⎥
⎢-0.0631737081780548  -0.0956499775890643   0.993408357314476   -0.31358538980296⎥
⎢                                                                                ⎥
⎣         0                    0                    0                   1        ⎦